// Planteles reales (lista probable / convocados recientes) para selecciones top.
// Para los equipos no listados acá, se usa el generador genérico de mock-data.ts.
import type { Player } from "./mock-data";

type RawPlayer = {
  name: string;
  number: number;
  position: Player["position"];
  age: number;
  club: string;
};

// Helper: marca rareza por dorsal/posición
function rarityFor(p: RawPlayer, isStar: boolean): Player["rarity"] {
  if (isStar) return "legendary";
  if (p.number === 1 || p.number === 9 || p.number === 7 || p.number === 11) return "epic";
  if (p.position === "POR") return "rare";
  return "common";
}

function build(teamId: string, players: RawPlayer[], stars: string[]): Player[] {
  return players.map((p) => ({
    id: `${teamId}-${p.number}`,
    name: p.name,
    number: p.number,
    position: p.position,
    age: p.age,
    club: p.club,
    rarity: rarityFor(p, stars.includes(p.name)),
  }));
}

// === ARGENTINA ===
const ARG: RawPlayer[] = [
  { number: 1, name: "Emiliano Martínez", position: "POR", age: 33, club: "Aston Villa" },
  { number: 12, name: "Gerónimo Rulli", position: "POR", age: 33, club: "Marsella" },
  { number: 23, name: "Walter Benítez", position: "POR", age: 32, club: "PSV" },
  { number: 2, name: "Lisandro Martínez", position: "DEF", age: 27, club: "Manchester United" },
  { number: 3, name: "Nicolás Tagliafico", position: "DEF", age: 33, club: "Lyon" },
  { number: 4, name: "Gonzalo Montiel", position: "DEF", age: 28, club: "River Plate" },
  { number: 6, name: "Germán Pezzella", position: "DEF", age: 34, club: "River Plate" },
  { number: 13, name: "Cristian Romero", position: "DEF", age: 27, club: "Tottenham" },
  { number: 17, name: "Nahuel Molina", position: "DEF", age: 27, club: "Atlético Madrid" },
  { number: 19, name: "Nicolás Otamendi", position: "DEF", age: 37, club: "Benfica" },
  { number: 25, name: "Marcos Senesi", position: "DEF", age: 28, club: "Bournemouth" },
  { number: 5, name: "Leandro Paredes", position: "MED", age: 31, club: "Boca Juniors" },
  { number: 7, name: "Rodrigo De Paul", position: "MED", age: 31, club: "Atlético Madrid" },
  { number: 8, name: "Enzo Fernández", position: "MED", age: 24, club: "Chelsea" },
  { number: 14, name: "Exequiel Palacios", position: "MED", age: 27, club: "Bayer Leverkusen" },
  { number: 18, name: "Guido Rodríguez", position: "MED", age: 31, club: "West Ham" },
  { number: 20, name: "Alexis Mac Allister", position: "MED", age: 26, club: "Liverpool" },
  { number: 24, name: "Thiago Almada", position: "MED", age: 24, club: "Lyon" },
  { number: 26, name: "Nico Paz", position: "MED", age: 21, club: "Como" },
  { number: 9, name: "Julián Álvarez", position: "DEL", age: 25, club: "Atlético Madrid" },
  { number: 10, name: "Lionel Messi", position: "DEL", age: 38, club: "Inter Miami" },
  { number: 11, name: "Ángel Di María", position: "DEL", age: 37, club: "Benfica" },
  { number: 15, name: "Nicolás González", position: "DEL", age: 27, club: "Juventus" },
  { number: 16, name: "Giovani Lo Celso", position: "MED", age: 29, club: "Real Betis" },
  { number: 21, name: "Lautaro Martínez", position: "DEL", age: 28, club: "Inter" },
  { number: 22, name: "Alejandro Garnacho", position: "DEL", age: 21, club: "Manchester United" },
];

// === BRASIL ===
const BRA: RawPlayer[] = [
  { number: 1, name: "Alisson", position: "POR", age: 33, club: "Liverpool" },
  { number: 12, name: "Bento", position: "POR", age: 26, club: "Al-Nassr" },
  { number: 23, name: "Ederson", position: "POR", age: 32, club: "Manchester City" },
  { number: 2, name: "Danilo", position: "DEF", age: 34, club: "Flamengo" },
  { number: 3, name: "Marquinhos", position: "DEF", age: 31, club: "PSG" },
  { number: 4, name: "Éder Militão", position: "DEF", age: 27, club: "Real Madrid" },
  { number: 6, name: "Wendell", position: "DEF", age: 32, club: "Porto" },
  { number: 13, name: "Bremer", position: "DEF", age: 28, club: "Juventus" },
  { number: 14, name: "Gabriel Magalhães", position: "DEF", age: 27, club: "Arsenal" },
  { number: 16, name: "Vanderson", position: "DEF", age: 24, club: "Mónaco" },
  { number: 22, name: "Yan Couto", position: "DEF", age: 23, club: "Borussia Dortmund" },
  { number: 5, name: "Casemiro", position: "MED", age: 33, club: "Manchester United" },
  { number: 7, name: "Lucas Paquetá", position: "MED", age: 28, club: "West Ham" },
  { number: 8, name: "Bruno Guimarães", position: "MED", age: 28, club: "Newcastle" },
  { number: 15, name: "André", position: "MED", age: 24, club: "Wolves" },
  { number: 17, name: "João Gomes", position: "MED", age: 24, club: "Wolves" },
  { number: 18, name: "Gerson", position: "MED", age: 28, club: "Zenit" },
  { number: 25, name: "Andreas Pereira", position: "MED", age: 29, club: "Fulham" },
  { number: 9, name: "Endrick", position: "DEL", age: 19, club: "Real Madrid" },
  { number: 10, name: "Rodrygo", position: "DEL", age: 25, club: "Real Madrid" },
  { number: 11, name: "Vinícius Júnior", position: "DEL", age: 25, club: "Real Madrid" },
  { number: 19, name: "Raphinha", position: "DEL", age: 28, club: "Barcelona" },
  { number: 20, name: "Savinho", position: "DEL", age: 21, club: "Manchester City" },
  { number: 21, name: "Estêvão", position: "DEL", age: 18, club: "Chelsea" },
  { number: 24, name: "Matheus Cunha", position: "DEL", age: 26, club: "Manchester United" },
  { number: 26, name: "Igor Jesus", position: "DEL", age: 24, club: "Nottingham Forest" },
];

// === FRANCIA ===
const FRA: RawPlayer[] = [
  { number: 1, name: "Mike Maignan", position: "POR", age: 30, club: "Milan" },
  { number: 16, name: "Brice Samba", position: "POR", age: 31, club: "Lens" },
  { number: 23, name: "Lucas Chevalier", position: "POR", age: 24, club: "PSG" },
  { number: 2, name: "Jules Koundé", position: "DEF", age: 27, club: "Barcelona" },
  { number: 3, name: "Theo Hernández", position: "DEF", age: 28, club: "Al-Hilal" },
  { number: 4, name: "Dayot Upamecano", position: "DEF", age: 27, club: "Bayern Munich" },
  { number: 5, name: "Jonathan Clauss", position: "DEF", age: 33, club: "Niza" },
  { number: 13, name: "William Saliba", position: "DEF", age: 24, club: "Arsenal" },
  { number: 17, name: "Lucas Digne", position: "DEF", age: 32, club: "Aston Villa" },
  { number: 22, name: "Malo Gusto", position: "DEF", age: 22, club: "Chelsea" },
  { number: 24, name: "Ibrahima Konaté", position: "DEF", age: 26, club: "Liverpool" },
  { number: 6, name: "Eduardo Camavinga", position: "MED", age: 23, club: "Real Madrid" },
  { number: 8, name: "Aurélien Tchouaméni", position: "MED", age: 25, club: "Real Madrid" },
  { number: 14, name: "Adrien Rabiot", position: "MED", age: 30, club: "Marsella" },
  { number: 15, name: "Manu Koné", position: "MED", age: 24, club: "Roma" },
  { number: 18, name: "Warren Zaïre-Emery", position: "MED", age: 19, club: "PSG" },
  { number: 25, name: "Khéphren Thuram", position: "MED", age: 24, club: "Juventus" },
  { number: 7, name: "Ousmane Dembélé", position: "DEL", age: 28, club: "PSG" },
  { number: 9, name: "Olivier Giroud", position: "DEL", age: 39, club: "Lille" },
  { number: 10, name: "Kylian Mbappé", position: "DEL", age: 27, club: "Real Madrid" },
  { number: 11, name: "Bradley Barcola", position: "DEL", age: 23, club: "PSG" },
  { number: 12, name: "Randal Kolo Muani", position: "DEL", age: 27, club: "Tottenham" },
  { number: 19, name: "Marcus Thuram", position: "DEL", age: 28, club: "Inter" },
  { number: 20, name: "Kingsley Coman", position: "DEL", age: 29, club: "Al-Nassr" },
  { number: 21, name: "Michael Olise", position: "DEL", age: 24, club: "Bayern Munich" },
  { number: 26, name: "Désiré Doué", position: "DEL", age: 20, club: "PSG" },
];

// === ESPAÑA ===
const ESP: RawPlayer[] = [
  { number: 1, name: "Unai Simón", position: "POR", age: 28, club: "Athletic Club" },
  { number: 13, name: "David Raya", position: "POR", age: 30, club: "Arsenal" },
  { number: 23, name: "Álex Remiro", position: "POR", age: 30, club: "Real Sociedad" },
  { number: 2, name: "Pedro Porro", position: "DEF", age: 26, club: "Tottenham" },
  { number: 3, name: "Robin Le Normand", position: "DEF", age: 29, club: "Atlético Madrid" },
  { number: 4, name: "Pau Cubarsí", position: "DEF", age: 18, club: "Barcelona" },
  { number: 5, name: "Dani Vivian", position: "DEF", age: 26, club: "Athletic Club" },
  { number: 14, name: "Aymeric Laporte", position: "DEF", age: 31, club: "Athletic Club" },
  { number: 17, name: "Marc Cucurella", position: "DEF", age: 27, club: "Chelsea" },
  { number: 18, name: "Dani Carvajal", position: "DEF", age: 33, club: "Real Madrid" },
  { number: 22, name: "Marcos Llorente", position: "DEF", age: 30, club: "Atlético Madrid" },
  { number: 6, name: "Mikel Merino", position: "MED", age: 29, club: "Arsenal" },
  { number: 8, name: "Fabián Ruiz", position: "MED", age: 29, club: "PSG" },
  { number: 10, name: "Pedri", position: "MED", age: 23, club: "Barcelona" },
  { number: 15, name: "Álex Baena", position: "MED", age: 24, club: "Atlético Madrid" },
  { number: 16, name: "Rodri", position: "MED", age: 29, club: "Manchester City" },
  { number: 20, name: "Martín Zubimendi", position: "MED", age: 26, club: "Arsenal" },
  { number: 7, name: "Álvaro Morata", position: "DEL", age: 33, club: "Como" },
  { number: 9, name: "Joselu", position: "DEL", age: 35, club: "Al-Gharafa" },
  { number: 11, name: "Ferran Torres", position: "DEL", age: 25, club: "Barcelona" },
  { number: 12, name: "Yéremy Pino", position: "DEL", age: 23, club: "Crystal Palace" },
  { number: 19, name: "Lamine Yamal", position: "DEL", age: 18, club: "Barcelona" },
  { number: 21, name: "Mikel Oyarzabal", position: "DEL", age: 28, club: "Real Sociedad" },
  { number: 24, name: "Ayoze Pérez", position: "DEL", age: 32, club: "Villarreal" },
  { number: 25, name: "Samu Aghehowa", position: "DEL", age: 21, club: "Porto" },
  { number: 26, name: "Nico Williams", position: "DEL", age: 23, club: "Athletic Club" },
];

// === INGLATERRA ===
const ING: RawPlayer[] = [
  { number: 1, name: "Jordan Pickford", position: "POR", age: 31, club: "Everton" },
  { number: 13, name: "Dean Henderson", position: "POR", age: 28, club: "Crystal Palace" },
  { number: 23, name: "James Trafford", position: "POR", age: 23, club: "Manchester City" },
  { number: 2, name: "Kyle Walker", position: "DEF", age: 35, club: "Burnley" },
  { number: 3, name: "Luke Shaw", position: "DEF", age: 30, club: "Manchester United" },
  { number: 5, name: "John Stones", position: "DEF", age: 31, club: "Manchester City" },
  { number: 6, name: "Marc Guéhi", position: "DEF", age: 25, club: "Crystal Palace" },
  { number: 12, name: "Kieran Trippier", position: "DEF", age: 35, club: "Newcastle" },
  { number: 14, name: "Ezri Konsa", position: "DEF", age: 28, club: "Aston Villa" },
  { number: 15, name: "Levi Colwill", position: "DEF", age: 22, club: "Chelsea" },
  { number: 22, name: "Tino Livramento", position: "DEF", age: 23, club: "Newcastle" },
  { number: 4, name: "Declan Rice", position: "MED", age: 26, club: "Arsenal" },
  { number: 8, name: "Jordan Henderson", position: "MED", age: 35, club: "Brentford" },
  { number: 10, name: "Jude Bellingham", position: "MED", age: 22, club: "Real Madrid" },
  { number: 16, name: "Conor Gallagher", position: "MED", age: 25, club: "Atlético Madrid" },
  { number: 17, name: "Cole Palmer", position: "MED", age: 23, club: "Chelsea" },
  { number: 19, name: "Adam Wharton", position: "MED", age: 21, club: "Crystal Palace" },
  { number: 26, name: "Morgan Rogers", position: "MED", age: 23, club: "Aston Villa" },
  { number: 7, name: "Bukayo Saka", position: "DEL", age: 24, club: "Arsenal" },
  { number: 9, name: "Harry Kane", position: "DEL", age: 32, club: "Bayern Munich" },
  { number: 11, name: "Phil Foden", position: "DEL", age: 25, club: "Manchester City" },
  { number: 18, name: "Anthony Gordon", position: "DEL", age: 24, club: "Newcastle" },
  { number: 20, name: "Marcus Rashford", position: "DEL", age: 28, club: "Aston Villa" },
  { number: 21, name: "Eberechi Eze", position: "DEL", age: 27, club: "Arsenal" },
  { number: 24, name: "Ollie Watkins", position: "DEL", age: 30, club: "Aston Villa" },
  { number: 25, name: "Noni Madueke", position: "DEL", age: 23, club: "Arsenal" },
];

// === PORTUGAL ===
const POR_SQUAD: RawPlayer[] = [
  { number: 1, name: "Diogo Costa", position: "POR", age: 26, club: "Porto" },
  { number: 12, name: "Rui Silva", position: "POR", age: 31, club: "Real Betis" },
  { number: 22, name: "José Sá", position: "POR", age: 32, club: "Wolves" },
  { number: 2, name: "Diogo Dalot", position: "DEF", age: 26, club: "Manchester United" },
  { number: 3, name: "Rúben Dias", position: "DEF", age: 28, club: "Manchester City" },
  { number: 4, name: "António Silva", position: "DEF", age: 22, club: "Benfica" },
  { number: 5, name: "Nuno Mendes", position: "DEF", age: 23, club: "PSG" },
  { number: 13, name: "Renato Veiga", position: "DEF", age: 22, club: "Villarreal" },
  { number: 14, name: "Gonçalo Inácio", position: "DEF", age: 24, club: "Sporting CP" },
  { number: 19, name: "Nélson Semedo", position: "DEF", age: 31, club: "Wolves" },
  { number: 20, name: "João Cancelo", position: "DEF", age: 31, club: "Al-Hilal" },
  { number: 6, name: "João Palhinha", position: "MED", age: 30, club: "Tottenham" },
  { number: 8, name: "Bruno Fernandes", position: "MED", age: 31, club: "Manchester United" },
  { number: 16, name: "Vitinha", position: "MED", age: 25, club: "PSG" },
  { number: 18, name: "Rúben Neves", position: "MED", age: 28, club: "Al-Hilal" },
  { number: 23, name: "Matheus Nunes", position: "MED", age: 27, club: "Manchester City" },
  { number: 25, name: "Otávio", position: "MED", age: 30, club: "Al-Nassr" },
  { number: 7, name: "Cristiano Ronaldo", position: "DEL", age: 40, club: "Al-Nassr" },
  { number: 9, name: "Gonçalo Ramos", position: "DEL", age: 24, club: "PSG" },
  { number: 10, name: "Bernardo Silva", position: "MED", age: 31, club: "Manchester City" },
  { number: 11, name: "João Félix", position: "DEL", age: 26, club: "Al-Nassr" },
  { number: 15, name: "Rafael Leão", position: "DEL", age: 26, club: "Milan" },
  { number: 17, name: "Pedro Neto", position: "DEL", age: 25, club: "Chelsea" },
  { number: 21, name: "Diogo Jota", position: "DEL", age: 28, club: "Liverpool" },
  { number: 24, name: "Francisco Conceição", position: "DEL", age: 22, club: "Juventus" },
  { number: 26, name: "Pedro Gonçalves", position: "MED", age: 27, club: "Sporting CP" },
];

// === ALEMANIA ===
const GER: RawPlayer[] = [
  { number: 1, name: "Marc-André ter Stegen", position: "POR", age: 33, club: "Barcelona" },
  { number: 12, name: "Oliver Baumann", position: "POR", age: 35, club: "Hoffenheim" },
  { number: 22, name: "Alexander Nübel", position: "POR", age: 29, club: "Stuttgart" },
  { number: 2, name: "Antonio Rüdiger", position: "DEF", age: 32, club: "Real Madrid" },
  { number: 3, name: "David Raum", position: "DEF", age: 27, club: "RB Leipzig" },
  { number: 4, name: "Jonathan Tah", position: "DEF", age: 29, club: "Bayern Munich" },
  { number: 5, name: "Nico Schlotterbeck", position: "DEF", age: 26, club: "Borussia Dortmund" },
  { number: 15, name: "Nathaniel Brown", position: "DEF", age: 22, club: "Eintracht Frankfurt" },
  { number: 16, name: "Waldemar Anton", position: "DEF", age: 29, club: "Borussia Dortmund" },
  { number: 23, name: "Robin Koch", position: "DEF", age: 29, club: "Eintracht Frankfurt" },
  { number: 24, name: "Joshua Kimmich", position: "MED", age: 30, club: "Bayern Munich" },
  { number: 6, name: "Pascal Groß", position: "MED", age: 34, club: "Borussia Dortmund" },
  { number: 8, name: "Leon Goretzka", position: "MED", age: 30, club: "Bayern Munich" },
  { number: 17, name: "Florian Wirtz", position: "MED", age: 22, club: "Liverpool" },
  { number: 19, name: "Aleksandar Pavlović", position: "MED", age: 21, club: "Bayern Munich" },
  { number: 21, name: "İlkay Gündoğan", position: "MED", age: 35, club: "Galatasaray" },
  { number: 25, name: "Angelo Stiller", position: "MED", age: 24, club: "Stuttgart" },
  { number: 7, name: "Kai Havertz", position: "DEL", age: 26, club: "Arsenal" },
  {
    number: 9,
    name: "Tim Kleindienst",
    position: "DEL",
    age: 30,
    club: "Borussia Mönchengladbach",
  },
  { number: 10, name: "Jamal Musiala", position: "MED", age: 22, club: "Bayern Munich" },
  { number: 11, name: "Karim Adeyemi", position: "DEL", age: 23, club: "Borussia Dortmund" },
  { number: 13, name: "Serge Gnabry", position: "DEL", age: 30, club: "Bayern Munich" },
  { number: 14, name: "Maximilian Beier", position: "DEL", age: 23, club: "Borussia Dortmund" },
  { number: 18, name: "Leroy Sané", position: "DEL", age: 29, club: "Galatasaray" },
  { number: 20, name: "Niclas Füllkrug", position: "DEL", age: 32, club: "West Ham" },
  { number: 26, name: "Deniz Undav", position: "DEL", age: 29, club: "Stuttgart" },
];

// === PAÍSES BAJOS ===
const NED: RawPlayer[] = [
  { number: 1, name: "Bart Verbruggen", position: "POR", age: 23, club: "Brighton" },
  { number: 13, name: "Mark Flekken", position: "POR", age: 32, club: "Bayer Leverkusen" },
  { number: 23, name: "Nick Olij", position: "POR", age: 30, club: "Sparta Rotterdam" },
  { number: 2, name: "Jurriën Timber", position: "DEF", age: 24, club: "Arsenal" },
  { number: 3, name: "Matthijs de Ligt", position: "DEF", age: 26, club: "Manchester United" },
  { number: 4, name: "Virgil van Dijk", position: "DEF", age: 34, club: "Liverpool" },
  { number: 5, name: "Nathan Aké", position: "DEF", age: 30, club: "Manchester City" },
  { number: 12, name: "Denzel Dumfries", position: "DEF", age: 29, club: "Inter" },
  { number: 15, name: "Micky van de Ven", position: "DEF", age: 24, club: "Tottenham" },
  { number: 17, name: "Daley Blind", position: "DEF", age: 35, club: "Girona" },
  { number: 22, name: "Lutsharel Geertruida", position: "DEF", age: 25, club: "RB Leipzig" },
  { number: 6, name: "Ryan Gravenberch", position: "MED", age: 23, club: "Liverpool" },
  { number: 8, name: "Jerdy Schouten", position: "MED", age: 28, club: "PSV" },
  { number: 14, name: "Tijjani Reijnders", position: "MED", age: 27, club: "Manchester City" },
  { number: 18, name: "Frenkie de Jong", position: "MED", age: 28, club: "Barcelona" },
  { number: 20, name: "Joey Veerman", position: "MED", age: 26, club: "PSV" },
  { number: 25, name: "Quinten Timber", position: "MED", age: 24, club: "Feyenoord" },
  { number: 7, name: "Xavi Simons", position: "MED", age: 22, club: "Tottenham" },
  { number: 9, name: "Wout Weghorst", position: "DEL", age: 33, club: "Ajax" },
  { number: 10, name: "Memphis Depay", position: "DEL", age: 31, club: "Corinthians" },
  { number: 11, name: "Cody Gakpo", position: "DEL", age: 26, club: "Liverpool" },
  { number: 16, name: "Brian Brobbey", position: "DEL", age: 23, club: "Sunderland" },
  { number: 19, name: "Donyell Malen", position: "DEL", age: 26, club: "Aston Villa" },
  { number: 21, name: "Jeremie Frimpong", position: "DEF", age: 24, club: "Liverpool" },
  { number: 24, name: "Justin Kluivert", position: "DEL", age: 26, club: "Bournemouth" },
  { number: 26, name: "Emanuel Emegha", position: "DEL", age: 22, club: "Strasbourg" },
];

// === URUGUAY ===
const URU: RawPlayer[] = [
  { number: 1, name: "Sergio Rochet", position: "POR", age: 32, club: "Internacional" },
  { number: 12, name: "Santiago Mele", position: "POR", age: 28, club: "Junior" },
  { number: 23, name: "Franco Israel", position: "POR", age: 25, club: "Sporting CP" },
  { number: 2, name: "José María Giménez", position: "DEF", age: 30, club: "Atlético Madrid" },
  { number: 3, name: "Ronald Araújo", position: "DEF", age: 26, club: "Barcelona" },
  { number: 4, name: "Guillermo Varela", position: "DEF", age: 32, club: "Flamengo" },
  { number: 6, name: "Mathías Olivera", position: "DEF", age: 28, club: "Napoli" },
  { number: 13, name: "Sebastián Cáceres", position: "DEF", age: 26, club: "América" },
  { number: 17, name: "Matías Viña", position: "DEF", age: 28, club: "Flamengo" },
  { number: 19, name: "Santiago Bueno", position: "DEF", age: 26, club: "Wolves" },
  { number: 22, name: "Nahitan Nández", position: "DEF", age: 30, club: "Al-Qadsiah" },
  { number: 5, name: "Manuel Ugarte", position: "MED", age: 24, club: "Manchester United" },
  { number: 7, name: "Nicolás de la Cruz", position: "MED", age: 28, club: "Flamengo" },
  { number: 8, name: "Federico Valverde", position: "MED", age: 27, club: "Real Madrid" },
  { number: 14, name: "Lucas Torreira", position: "MED", age: 29, club: "Galatasaray" },
  { number: 15, name: "Federico Viñas", position: "DEL", age: 27, club: "León" },
  { number: 16, name: "Mathías Olivera", position: "MED", age: 28, club: "Napoli" },
  { number: 18, name: "Maximiliano Araújo", position: "MED", age: 25, club: "Sporting CP" },
  { number: 25, name: "Rodrigo Bentancur", position: "MED", age: 28, club: "Tottenham" },
  { number: 9, name: "Darwin Núñez", position: "DEL", age: 26, club: "Al-Hilal" },
  { number: 10, name: "Giorgian de Arrascaeta", position: "MED", age: 31, club: "Flamengo" },
  { number: 11, name: "Facundo Pellistri", position: "DEL", age: 23, club: "Panathinaikos" },
  { number: 20, name: "Maxi Gómez", position: "DEL", age: 29, club: "Cádiz" },
  { number: 21, name: "Cristian Olivera", position: "DEL", age: 23, club: "LAFC" },
  { number: 24, name: "Brian Rodríguez", position: "DEL", age: 25, club: "América" },
  { number: 26, name: "Rodrigo Aguirre", position: "DEL", age: 31, club: "América" },
];

// === COLOMBIA ===
const COL: RawPlayer[] = [
  { number: 1, name: "Camilo Vargas", position: "POR", age: 36, club: "Atlas" },
  { number: 12, name: "Kevin Mier", position: "POR", age: 25, club: "Cruz Azul" },
  { number: 22, name: "Álvaro Montero", position: "POR", age: 30, club: "Vélez Sarsfield" },
  { number: 2, name: "Daniel Muñoz", position: "DEF", age: 29, club: "Crystal Palace" },
  { number: 3, name: "Jhon Lucumí", position: "DEF", age: 27, club: "Bologna" },
  { number: 4, name: "Santiago Arias", position: "DEF", age: 33, club: "Bahía" },
  { number: 5, name: "Yerson Mosquera", position: "DEF", age: 24, club: "Wolves" },
  { number: 13, name: "Yerry Mina", position: "DEF", age: 31, club: "Cagliari" },
  { number: 17, name: "Johan Mojica", position: "DEF", age: 33, club: "Mallorca" },
  { number: 23, name: "Davinson Sánchez", position: "DEF", age: 29, club: "Galatasaray" },
  { number: 25, name: "Carlos Cuesta", position: "DEF", age: 26, club: "Galatasaray" },
  { number: 6, name: "Richard Ríos", position: "MED", age: 25, club: "Benfica" },
  { number: 8, name: "Jefferson Lerma", position: "MED", age: 31, club: "Crystal Palace" },
  { number: 14, name: "Jorge Carrascal", position: "MED", age: 27, club: "Flamengo" },
  { number: 15, name: "Mateus Uribe", position: "MED", age: 34, club: "Al-Sadd" },
  { number: 16, name: "Jefferson Lerma", position: "MED", age: 31, club: "Crystal Palace" },
  { number: 20, name: "Juan Quintero", position: "MED", age: 32, club: "Junior" },
  { number: 7, name: "Luis Díaz", position: "DEL", age: 28, club: "Bayern Munich" },
  { number: 9, name: "Jhon Córdoba", position: "DEL", age: 32, club: "Krasnodar" },
  { number: 10, name: "James Rodríguez", position: "MED", age: 34, club: "León" },
  { number: 11, name: "Jhon Arias", position: "DEL", age: 27, club: "Wolves" },
  { number: 18, name: "Rafael Borré", position: "DEL", age: 30, club: "Internacional" },
  { number: 19, name: "Luis Sinisterra", position: "DEL", age: 26, club: "Cruzeiro" },
  { number: 21, name: "Jhon Durán", position: "DEL", age: 22, club: "Fenerbahçe" },
  { number: 24, name: "Marino Hinestroza", position: "DEL", age: 23, club: "Atlético Nacional" },
  { number: 26, name: "Yaser Asprilla", position: "MED", age: 22, club: "Girona" },
];

// === MÉXICO ===
const MEX: RawPlayer[] = [
  { number: 1, name: "Guillermo Ochoa", position: "POR", age: 40, club: "AVS" },
  { number: 12, name: "Luis Malagón", position: "POR", age: 28, club: "América" },
  { number: 13, name: "Raúl Rangel", position: "POR", age: 25, club: "Chivas" },
  { number: 2, name: "Julián Araujo", position: "DEF", age: 24, club: "Bournemouth" },
  { number: 3, name: "César Montes", position: "DEF", age: 28, club: "Lokomotiv Moscú" },
  { number: 4, name: "Edson Álvarez", position: "MED", age: 28, club: "Fenerbahçe" },
  { number: 5, name: "Johan Vásquez", position: "DEF", age: 27, club: "Génova" },
  { number: 14, name: "Erick Sánchez", position: "MED", age: 26, club: "América" },
  { number: 15, name: "Israel Reyes", position: "DEF", age: 25, club: "América" },
  { number: 19, name: "Jesús Gallardo", position: "DEF", age: 31, club: "Toluca" },
  { number: 23, name: "Jorge Sánchez", position: "DEF", age: 28, club: "Cruz Azul" },
  { number: 6, name: "Gerardo Arteaga", position: "DEF", age: 27, club: "Genk" },
  { number: 8, name: "Carlos Rodríguez", position: "MED", age: 28, club: "Cruz Azul" },
  { number: 16, name: "Luis Romo", position: "MED", age: 30, club: "Rayados" },
  { number: 17, name: "Orbelín Pineda", position: "MED", age: 30, club: "AEK Atenas" },
  { number: 18, name: "Luis Chávez", position: "MED", age: 29, club: "Pachuca" },
  { number: 24, name: "Marcel Ruiz", position: "MED", age: 25, club: "Toluca" },
  { number: 7, name: "Alexis Vega", position: "DEL", age: 28, club: "Toluca" },
  { number: 9, name: "Raúl Jiménez", position: "DEL", age: 34, club: "Fulham" },
  { number: 10, name: "Hirving Lozano", position: "DEL", age: 30, club: "San Diego FC" },
  { number: 11, name: "Santiago Giménez", position: "DEL", age: 24, club: "Milan" },
  { number: 20, name: "Henry Martín", position: "DEL", age: 32, club: "América" },
  { number: 21, name: "Diego Lainez", position: "DEL", age: 25, club: "Tigres" },
  { number: 22, name: "Uriel Antuna", position: "DEL", age: 28, club: "Cruz Azul" },
  { number: 25, name: "Roberto Alvarado", position: "DEL", age: 27, club: "Chivas" },
  { number: 26, name: "Armando González", position: "DEL", age: 22, club: "Chivas" },
];

// === ESTADOS UNIDOS ===
const USA: RawPlayer[] = [
  { number: 1, name: "Matt Turner", position: "POR", age: 31, club: "Crystal Palace" },
  { number: 12, name: "Patrick Schulte", position: "POR", age: 24, club: "Columbus Crew" },
  { number: 22, name: "Matt Freese", position: "POR", age: 27, club: "NYCFC" },
  { number: 2, name: "Sergiño Dest", position: "DEF", age: 25, club: "PSV" },
  { number: 3, name: "Chris Richards", position: "DEF", age: 25, club: "Crystal Palace" },
  { number: 4, name: "Tyler Adams", position: "MED", age: 26, club: "Bournemouth" },
  { number: 5, name: "Antonee Robinson", position: "DEF", age: 28, club: "Fulham" },
  { number: 13, name: "Tim Ream", position: "DEF", age: 38, club: "Charlotte FC" },
  { number: 14, name: "Joe Scally", position: "DEF", age: 22, club: "Borussia Mönchengladbach" },
  { number: 15, name: "Auston Trusty", position: "DEF", age: 27, club: "Celtic" },
  { number: 23, name: "Cameron Carter-Vickers", position: "DEF", age: 27, club: "Celtic" },
  { number: 6, name: "Yunus Musah", position: "MED", age: 22, club: "Atalanta" },
  { number: 8, name: "Weston McKennie", position: "MED", age: 27, club: "Juventus" },
  { number: 16, name: "Aidan Morris", position: "MED", age: 23, club: "Middlesbrough" },
  { number: 17, name: "Malik Tillman", position: "MED", age: 23, club: "Bayer Leverkusen" },
  { number: 18, name: "Johnny Cardoso", position: "MED", age: 24, club: "Atlético Madrid" },
  { number: 25, name: "Tanner Tessmann", position: "MED", age: 24, club: "Lyon" },
  { number: 7, name: "Giovanni Reyna", position: "MED", age: 22, club: "Borussia Dortmund" },
  { number: 9, name: "Josh Sargent", position: "DEL", age: 25, club: "Norwich" },
  { number: 10, name: "Christian Pulisic", position: "DEL", age: 27, club: "Milan" },
  { number: 11, name: "Brenden Aaronson", position: "DEL", age: 25, club: "Leeds United" },
  { number: 19, name: "Haji Wright", position: "DEL", age: 27, club: "Coventry City" },
  { number: 20, name: "Folarin Balogun", position: "DEL", age: 24, club: "Mónaco" },
  { number: 21, name: "Tim Weah", position: "DEL", age: 25, club: "Marsella" },
  { number: 24, name: "Diego Luna", position: "MED", age: 22, club: "Real Salt Lake" },
  { number: 26, name: "Patrick Agyemang", position: "DEL", age: 25, club: "Charlotte FC" },
];

// === BÉLGICA ===
const BEL: RawPlayer[] = [
  { number: 1, name: "Koen Casteels", position: "POR", age: 33, club: "Al-Qadsiah" },
  { number: 12, name: "Matz Sels", position: "POR", age: 33, club: "Nottingham Forest" },
  { number: 22, name: "Thomas Kaminski", position: "POR", age: 32, club: "Luton Town" },
  { number: 2, name: "Timothy Castagne", position: "DEF", age: 30, club: "Fulham" },
  { number: 3, name: "Arthur Theate", position: "DEF", age: 25, club: "Eintracht Frankfurt" },
  { number: 4, name: "Wout Faes", position: "DEF", age: 27, club: "Leicester City" },
  { number: 5, name: "Jan Vertonghen", position: "DEF", age: 38, club: "Anderlecht" },
  { number: 13, name: "Maxim De Cuyper", position: "DEF", age: 25, club: "Brighton" },
  { number: 15, name: "Zeno Debast", position: "DEF", age: 22, club: "Sporting CP" },
  { number: 18, name: "Brandon Mechele", position: "DEF", age: 32, club: "Club Brugge" },
  { number: 24, name: "Koni De Winter", position: "DEF", age: 23, club: "Milan" },
  { number: 6, name: "Axel Witsel", position: "DEF", age: 36, club: "Girona" },
  { number: 8, name: "Youri Tielemans", position: "MED", age: 28, club: "Aston Villa" },
  { number: 14, name: "Hans Vanaken", position: "MED", age: 33, club: "Club Brugge" },
  { number: 17, name: "Charles De Ketelaere", position: "MED", age: 24, club: "Atalanta" },
  { number: 19, name: "Leandro Trossard", position: "DEL", age: 30, club: "Arsenal" },
  { number: 25, name: "Arthur Vermeeren", position: "MED", age: 20, club: "Marsella" },
  { number: 7, name: "Kevin De Bruyne", position: "MED", age: 34, club: "Napoli" },
  { number: 9, name: "Romelu Lukaku", position: "DEL", age: 32, club: "Napoli" },
  { number: 10, name: "Jérémy Doku", position: "DEL", age: 23, club: "Manchester City" },
  { number: 11, name: "Yannick Carrasco", position: "DEL", age: 32, club: "Al-Shabab" },
  { number: 16, name: "Dodi Lukebakio", position: "DEL", age: 27, club: "Sevilla" },
  { number: 20, name: "Loïs Openda", position: "DEL", age: 25, club: "Juventus" },
  { number: 21, name: "Johan Bakayoko", position: "DEL", age: 22, club: "RB Leipzig" },
  { number: 23, name: "Michy Batshuayi", position: "DEL", age: 32, club: "Eintracht Frankfurt" },
  { number: 26, name: "Alexis Saelemaekers", position: "DEL", age: 26, club: "Milan" },
];

// === CROACIA ===
const CRO: RawPlayer[] = [
  { number: 1, name: "Dominik Livaković", position: "POR", age: 31, club: "Girona" },
  { number: 12, name: "Ivica Ivušić", position: "POR", age: 31, club: "Pafos" },
  { number: 23, name: "Nediljko Labrović", position: "POR", age: 26, club: "Rijeka" },
  { number: 2, name: "Josip Stanišić", position: "DEF", age: 25, club: "Bayern Munich" },
  { number: 3, name: "Marin Pongračić", position: "DEF", age: 28, club: "Fiorentina" },
  { number: 4, name: "Joško Gvardiol", position: "DEF", age: 24, club: "Manchester City" },
  { number: 5, name: "Martin Erlić", position: "DEF", age: 27, club: "Sassuolo" },
  { number: 6, name: "Josip Šutalo", position: "DEF", age: 25, club: "Ajax" },
  { number: 13, name: "Duje Ćaleta-Car", position: "DEF", age: 29, club: "Lyon" },
  { number: 19, name: "Borna Sosa", position: "DEF", age: 27, club: "Torino" },
  { number: 22, name: "Josip Juranović", position: "DEF", age: 30, club: "Union Berlin" },
  { number: 7, name: "Lovro Majer", position: "MED", age: 27, club: "Wolfsburgo" },
  { number: 8, name: "Mateo Kovačić", position: "MED", age: 31, club: "Manchester City" },
  { number: 10, name: "Luka Modrić", position: "MED", age: 40, club: "Milan" },
  { number: 11, name: "Marcelo Brozović", position: "MED", age: 33, club: "Al-Nassr" },
  { number: 14, name: "Luka Sučić", position: "MED", age: 23, club: "Real Sociedad" },
  { number: 15, name: "Mario Pašalić", position: "MED", age: 30, club: "Atalanta" },
  { number: 18, name: "Petar Sučić", position: "MED", age: 22, club: "Inter" },
  { number: 25, name: "Toni Fruk", position: "MED", age: 24, club: "Rijeka" },
  { number: 9, name: "Andrej Kramarić", position: "DEL", age: 34, club: "Hoffenheim" },
  { number: 16, name: "Ante Budimir", position: "DEL", age: 34, club: "Osasuna" },
  { number: 17, name: "Bruno Petković", position: "DEL", age: 31, club: "Vissel Kobe" },
  { number: 20, name: "Igor Matanović", position: "DEL", age: 22, club: "Eintracht Frankfurt" },
  { number: 21, name: "Marco Pašalić", position: "DEL", age: 24, club: "Orlando City" },
  { number: 24, name: "Petar Musa", position: "DEL", age: 27, club: "FC Dallas" },
  { number: 26, name: "Martin Baturina", position: "MED", age: 22, club: "Como" },
];

// === ITALIA ===
const ITA: RawPlayer[] = [
  { number: 1, name: "Gianluigi Donnarumma", position: "POR", age: 26, club: "Manchester City" },
  { number: 12, name: "Guglielmo Vicario", position: "POR", age: 28, club: "Tottenham" },
  { number: 22, name: "Michele Di Gregorio", position: "POR", age: 28, club: "Juventus" },
  { number: 2, name: "Giovanni Di Lorenzo", position: "DEF", age: 32, club: "Napoli" },
  { number: 3, name: "Federico Dimarco", position: "DEF", age: 28, club: "Inter" },
  { number: 4, name: "Alessandro Buongiorno", position: "DEF", age: 26, club: "Napoli" },
  { number: 5, name: "Riccardo Calafiori", position: "DEF", age: 23, club: "Arsenal" },
  { number: 13, name: "Matteo Gabbia", position: "DEF", age: 26, club: "Milan" },
  { number: 15, name: "Andrea Cambiaso", position: "DEF", age: 25, club: "Juventus" },
  { number: 19, name: "Destiny Udogie", position: "DEF", age: 23, club: "Tottenham" },
  { number: 23, name: "Alessandro Bastoni", position: "DEF", age: 26, club: "Inter" },
  { number: 6, name: "Manuel Locatelli", position: "MED", age: 27, club: "Juventus" },
  { number: 8, name: "Sandro Tonali", position: "MED", age: 25, club: "Newcastle" },
  { number: 14, name: "Davide Frattesi", position: "MED", age: 26, club: "Inter" },
  { number: 16, name: "Bryan Cristante", position: "MED", age: 30, club: "Roma" },
  { number: 18, name: "Nicolò Barella", position: "MED", age: 28, club: "Inter" },
  { number: 21, name: "Samuele Ricci", position: "MED", age: 24, club: "Milan" },
  { number: 25, name: "Nicolò Rovella", position: "MED", age: 23, club: "Lazio" },
  { number: 7, name: "Federico Chiesa", position: "DEL", age: 28, club: "Liverpool" },
  { number: 9, name: "Mateo Retegui", position: "DEL", age: 26, club: "Al-Qadsiah" },
  { number: 10, name: "Lorenzo Pellegrini", position: "MED", age: 29, club: "Roma" },
  { number: 11, name: "Giacomo Raspadori", position: "DEL", age: 25, club: "Atlético Madrid" },
  { number: 17, name: "Moise Kean", position: "DEL", age: 25, club: "Fiorentina" },
  { number: 20, name: "Mateo Politano", position: "DEL", age: 32, club: "Napoli" },
  { number: 24, name: "Andrea Pinamonti", position: "DEL", age: 26, club: "Genoa" },
  { number: 26, name: "Daniel Maldini", position: "MED", age: 24, club: "Atalanta" },
];

// Mapeo team_id → roster real
const REAL_SQUADS: Record<string, { players: RawPlayer[]; stars: string[] }> = {
  arg: {
    players: ARG,
    stars: ["Lionel Messi", "Julián Álvarez", "Emiliano Martínez", "Lautaro Martínez"],
  },
  bra: { players: BRA, stars: ["Vinícius Júnior", "Rodrygo", "Endrick", "Alisson"] },
  fra: { players: FRA, stars: ["Kylian Mbappé", "Ousmane Dembélé", "Aurélien Tchouaméni"] },
  esp: { players: ESP, stars: ["Lamine Yamal", "Pedri", "Rodri", "Nico Williams"] },
  ing: { players: ING, stars: ["Jude Bellingham", "Harry Kane", "Bukayo Saka", "Cole Palmer"] },
  por: {
    players: POR_SQUAD,
    stars: ["Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva", "Rafael Leão"],
  },
  ger: { players: GER, stars: ["Florian Wirtz", "Jamal Musiala", "Joshua Kimmich"] },
  ned: { players: NED, stars: ["Virgil van Dijk", "Cody Gakpo", "Frenkie de Jong"] },
  uru: { players: URU, stars: ["Federico Valverde", "Darwin Núñez", "Ronald Araújo"] },
  col: { players: COL, stars: ["Luis Díaz", "James Rodríguez", "Daniel Muñoz"] },
  mex: { players: MEX, stars: ["Santiago Giménez", "Edson Álvarez", "Hirving Lozano"] },
  usa: { players: USA, stars: ["Christian Pulisic", "Weston McKennie", "Folarin Balogun"] },
  bel: { players: BEL, stars: ["Kevin De Bruyne", "Romelu Lukaku", "Jérémy Doku"] },
  cro: { players: CRO, stars: ["Luka Modrić", "Joško Gvardiol", "Mateo Kovačić"] },
  ita: { players: ITA, stars: ["Gianluigi Donnarumma", "Sandro Tonali", "Federico Chiesa"] },
};

export function getRealRoster(teamId: string): Player[] | null {
  const squad = REAL_SQUADS[teamId];
  if (!squad) return null;
  return build(teamId, squad.players, squad.stars);
}

export function hasRealRoster(teamId: string): boolean {
  return teamId in REAL_SQUADS;
}
