// Planteles oficiales WC 2026 — todas las selecciones clasificadas.
import type { Player } from "./mock-data";

type RawPlayer = {
  name: string;
  position: Player["position"];
  club: string | null;
};

function rarityFor(pos: string, isStar: boolean): Player["rarity"] {
  if (isStar) return "legendary";
  if (pos === "POR") return "rare";
  return "common";
}

function build(teamId: string, players: RawPlayer[], stars: string[]): Player[] {
  return players.map((p, i) => ({
    id: `${teamId}-${i + 1}`,
    name: p.name,
    number: i + 1,
    position: p.position,
    age: 0,
    club: p.club ?? "",
    rarity: rarityFor(p.position, stars.includes(p.name)),
  }));
}

// === ALEMANIA ===
const GER: RawPlayer[] = [
  { name: "Oliver Baumann", position: "POR", club: "Hoffenheim" },
  { name: "Manuel Neuer", position: "POR", club: "Bayern Munich" },
  { name: "Alexander Nübel", position: "POR", club: "Stuttgart" },
  { name: "Waldemar Anton", position: "DEF", club: "Borussia Dortmund" },
  { name: "Nathaniel Brown", position: "DEF", club: "Eintracht Frankfurt" },
  { name: "Joshua Kimmich", position: "DEF", club: "Bayern Munich" },
  { name: "David Raum", position: "DEF", club: "RB Leipzig" },
  { name: "Antonio Rüdiger", position: "DEF", club: "Real Madrid" },
  { name: "Nico Schlotterbeck", position: "DEF", club: "Borussia Dortmund" },
  { name: "Jonathan Tah", position: "DEF", club: "Bayern Munich" },
  { name: "Malick Thiaw", position: "DEF", club: "Newcastle United" },
  { name: "Nadiem Amiri", position: "MED", club: "Mainz" },
  { name: "Leon Goretzka", position: "MED", club: "Bayern Munich" },
  { name: "Pascal Groß", position: "MED", club: "Brighton and Hove Albion" },
  { name: "Jamie Leweling", position: "MED", club: "Stuttgart" },
  { name: "Jamal Musiala", position: "MED", club: "Bayern Munich" },
  { name: "Felix Nmecha", position: "MED", club: "Borussia Dortmund" },
  { name: "Aleksandar Pavlovic", position: "MED", club: "Bayern Munich" },
  { name: "Angelo Stiller", position: "MED", club: "Stuttgart" },
  { name: "Florian Wirtz", position: "MED", club: "Liverpool" },
  { name: "Maximilian Beier", position: "DEL", club: "Borussia Dortmund" },
  { name: "Kai Havertz", position: "DEL", club: "Arsenal" },
  { name: "Lennart Karl", position: "DEL", club: "Bayern Munich" },
  { name: "Leroy Sané", position: "DEL", club: "Galatasaray" },
  { name: "Deniz Undav", position: "DEL", club: "Stuttgart" },
  { name: "Nick Woltemade", position: "DEL", club: "Newcastle United" },
];

// === ARGELIA ===
const ALG: RawPlayer[] = [
  { name: "Luca Zidane", position: "POR", club: "Granada" },
  { name: "Oussama Benbot", position: "POR", club: "USM Alger" },
  { name: "Melvin Mastil", position: "POR", club: "Stade Nyonnais" },
  { name: "Rafik Belghali", position: "DEF", club: "Hellas Verona" },
  { name: "Samir Chergui", position: "DEF", club: "Red Star FC" },
  { name: "Rayan Aït-Nouri", position: "DEF", club: "Manchester City" },
  { name: "Jaouen Hadjam", position: "DEF", club: "BSC Young Boys" },
  { name: "Aïssa Mandi", position: "DEF", club: "LOSC Lille" },
  { name: "Ramy Bensebaini", position: "DEF", club: "Borussia Dortmund" },
  { name: "Zineddine Belaïd", position: "DEF", club: "JS Kabylie" },
  { name: "Achref Abada", position: "DEF", club: "USM Alger" },
  { name: "Mohamed Amine Tougaï", position: "DEF", club: "Espérance de Tunis" },
  { name: "Nabil Bentaleb", position: "MED", club: "LOSC Lille" },
  { name: "Hicham Boudaoui", position: "MED", club: "Nice" },
  { name: "Houssem Aouar", position: "MED", club: "Al-Ittihad" },
  { name: "Farès Chaïbi", position: "MED", club: "Eintracht Frankfurt" },
  { name: "Ibrahim Maza", position: "MED", club: "Bayer Leverkusen" },
  { name: "Yacine Titraoui", position: "MED", club: "Charleroi" },
  { name: "Ramiz Zerrouki", position: "MED", club: "FC Twente" },
  { name: "Mohamed Amine Amoura", position: "DEL", club: "VfL Wolfsburg" },
  { name: "Nadhir Benbouali", position: "DEL", club: "Győr" },
  { name: "Adil Boulbina", position: "DEL", club: "Al-Duhail" },
  { name: "Farès Ghedjemis", position: "DEL", club: "Frosinone" },
  { name: "Amine Gouiri", position: "DEL", club: "Olympique de Marseille" },
  { name: "Anis Hadj Moussa", position: "DEL", club: "Feyenoord" },
  { name: "Riyad Mahrez", position: "DEL", club: "Al-Ahli" },
];

// === ARGENTINA ===
const ARG: RawPlayer[] = [
  { name: "Emiliano Martínez", position: "POR", club: "Aston Villa" },
  { name: "Gerónimo Rulli", position: "POR", club: "Marseille" },
  { name: "Juan Musso", position: "POR", club: "Atlético Madrid" },
  { name: "Leonardo Balerdi", position: "DEF", club: "Marseille" },
  { name: "Nicolás Tagliafico", position: "DEF", club: "Lyon" },
  { name: "Gonzalo Montiel", position: "DEF", club: "River Plate" },
  { name: "Lisandro Martínez", position: "DEF", club: "Manchester United" },
  { name: "Cristian Romero", position: "DEF", club: "Tottenham" },
  { name: "Nicolás Otamendi", position: "DEF", club: "Benfica" },
  { name: "Facundo Medina", position: "DEF", club: "Marseille" },
  { name: "Nahuel Molina", position: "DEF", club: "Atlético Madrid" },
  { name: "Leandro Paredes", position: "MED", club: "Boca Juniors" },
  { name: "Rodrigo De Paul", position: "MED", club: "Inter Miami" },
  { name: "Valentín Barco", position: "MED", club: "Strasbourg" },
  { name: "Giovani Lo Celso", position: "MED", club: "Real Betis" },
  { name: "Exequiel Palacios", position: "MED", club: "Bayer Leverkusen" },
  { name: "Enzo Fernández", position: "MED", club: "Chelsea" },
  { name: "Alexis Mac Allister", position: "MED", club: "Liverpool" },
  { name: "Julián Álvarez", position: "DEL", club: "Atlético Madrid" },
  { name: "Lionel Messi", position: "DEL", club: "Inter Miami" },
  { name: "Nicolás González", position: "DEL", club: "Atlético Madrid" },
  { name: "Thiago Almada", position: "DEL", club: "Atlético Madrid" },
  { name: "Giuliano Simeone", position: "DEL", club: "Atlético Madrid" },
  { name: "Nico Paz", position: "DEL", club: "Como" },
  { name: "José Manuel López", position: "DEL", club: "Palmeiras" },
  { name: "Lautaro Martínez", position: "DEL", club: "Inter Milan" },
];

// === AUSTRALIA ===
const AUS: RawPlayer[] = [
  { name: "Mathew Ryan", position: "POR", club: "Levante" },
  { name: "Paul Izzo", position: "POR", club: "Randers" },
  { name: "Thomas Beach", position: "POR", club: "Melbourne City" },
  { name: "Aziz Behich", position: "DEF", club: "Melbourne City" },
  { name: "Jordan Bos", position: "DEF", club: "Feyenoord" },
  { name: "Cameron Burgess", position: "DEF", club: "Swansea City" },
  { name: "Alessandro Circati", position: "DEF", club: "Parma" },
  { name: "Milos Degenek", position: "DEF", club: "APOEL" },
  { name: "Jason Geria", position: "DEF", club: "Albirex Niigata" },
  { name: "Lucas Herrington", position: "DEF", club: "Colorado Rapids" },
  { name: "Jacob Italiano", position: "DEF", club: "Grazer AK" },
  { name: "Harry Souttar", position: "DEF", club: "Leicester City" },
  { name: "Alexander Trewin", position: "DEF", club: "New York City FC" },
  { name: "Cammy Devlin", position: "MED", club: "Heart of Midlothian" },
  { name: "Ajdin Hrustic", position: "MED", club: "Heracles Almelo" },
  { name: "Jackson Irvine", position: "MED", club: "St Pauli" },
  { name: "Connor Metcalfe", position: "MED", club: "St Pauli" },
  { name: "Paul Okon-Engstler", position: "MED", club: "Sydney FC" },
  { name: "Aiden O'Neill", position: "MED", club: "New York City FC" },
  { name: "Nestory Irankunda", position: "DEL", club: "Watford" },
  { name: "Mathew Leckie", position: "DEL", club: "Melbourne City" },
  { name: "Awer Mabil", position: "DEL", club: "Castellón" },
  { name: "Mohamed Toure", position: "DEL", club: "Norwich City" },
  { name: "Nishan Velupillay", position: "DEL", club: "Melbourne Victory" },
  { name: "Cristian Volpato", position: "DEL", club: "Sassuolo" },
  { name: "Tete Yengi", position: "DEL", club: "Machida Zelvia" },
];

// === AUSTRIA ===
const AUT: RawPlayer[] = [
  { name: "Patrick Pentz", position: "POR", club: "Brøndby IF" },
  { name: "Alexander Schlager", position: "POR", club: "FC Salzburg" },
  { name: "Florian Wiegele", position: "POR", club: "Viktoria Plzeň" },
  { name: "David Affengruber", position: "DEF", club: "Elche" },
  { name: "David Alaba", position: "DEF", club: "Real Madrid" },
  { name: "Kevin Danso", position: "DEF", club: "Tottenham Hotspur" },
  { name: "Marco Friedl", position: "DEF", club: "Werder Bremen" },
  { name: "Philipp Lienhart", position: "DEF", club: "SC Freiburg" },
  { name: "Phillipp Mwene", position: "DEF", club: "Mainz 05" },
  { name: "Stefan Posch", position: "DEF", club: "Mainz 05" },
  { name: "Alexander Prass", position: "DEF", club: "TSG Hoffenheim" },
  { name: "Michael Svoboda", position: "DEF", club: "Venezia" },
  { name: "Christoph Baumgartner", position: "MED", club: "RB Leipzig" },
  { name: "Carney Chukwuemeka", position: "MED", club: "Borussia Dortmund" },
  { name: "Florian Grillitsch", position: "MED", club: "SC Braga" },
  { name: "Konrad Laimer", position: "MED", club: "Bayern München" },
  { name: "Marcel Sabitzer", position: "MED", club: "Borussia Dortmund" },
  { name: "Xaver Schlager", position: "MED", club: "RB Leipzig" },
  { name: "Nicolas Seiwald", position: "MED", club: "RB Leipzig" },
  { name: "Romano Schmid", position: "MED", club: "Werder Bremen" },
  { name: "Alessandro Schöpf", position: "MED", club: "Wolfsberger AC" },
  { name: "Paul Wanner", position: "MED", club: "PSV Eindhoven" },
  { name: "Patrick Wimmer", position: "MED", club: "VfL Wolfsburg" },
  { name: "Marko Arnautović", position: "DEL", club: "Crvena Zvezda" },
  { name: "Michael Gregoritsch", position: "DEL", club: "Augsburg" },
  { name: "Sasa Kalajdzic", position: "DEL", club: "LASK" },
];

// === BÉLGICA ===
const BEL: RawPlayer[] = [
  { name: "Thibaut Courtois", position: "POR", club: "Real Madrid" },
  { name: "Senne Lammens", position: "POR", club: "Manchester United" },
  { name: "Mike Penders", position: "POR", club: "Strasbourg" },
  { name: "Timothy Castagne", position: "DEF", club: "Fulham" },
  { name: "Zeno Debast", position: "DEF", club: "Sporting CP" },
  { name: "Maxim De Cuyper", position: "DEF", club: "Brighton" },
  { name: "Koni De Winter", position: "DEF", club: "AC Milan" },
  { name: "Brandon Mechele", position: "DEF", club: "Club Brugge" },
  { name: "Thomas Meunier", position: "DEF", club: "Lille" },
  { name: "Nathan Ngoy", position: "DEF", club: "Lille" },
  { name: "Joaquin Seys", position: "DEF", club: "Club Brugge" },
  { name: "Arthur Theate", position: "DEF", club: "Eintracht Frankfurt" },
  { name: "Kevin De Bruyne", position: "MED", club: "Napoli" },
  { name: "Amadou Onana", position: "MED", club: "Aston Villa" },
  { name: "Nicolas Raskin", position: "MED", club: "Rangers" },
  { name: "Youri Tielemans", position: "MED", club: "Aston Villa" },
  { name: "Hans Vanaken", position: "MED", club: "Club Brugge" },
  { name: "Axel Witsel", position: "MED", club: "Girona" },
  { name: "Charles De Ketelaere", position: "DEL", club: "Atalanta" },
  { name: "Jeremy Doku", position: "DEL", club: "Manchester City" },
  { name: "Matias Fernandez-Pardo", position: "DEL", club: "Lille" },
  { name: "Romelu Lukaku", position: "DEL", club: "Napoli" },
  { name: "Dodi Lukebakio", position: "DEL", club: "Sevilla" },
  { name: "Diego Moreira", position: "DEL", club: "Chelsea" },
  { name: "Alexis Saelemaekers", position: "DEL", club: "Milan" },
  { name: "Leandro Trossard", position: "DEL", club: "Arsenal" },
];

// === BOSNIA Y HERZEGOVINA ===
const BIH: RawPlayer[] = [
  { name: "Nikola Vasilj", position: "POR", club: "St Pauli" },
  { name: "Martin Zlomislic", position: "POR", club: "Rijeka" },
  { name: "Osman Hadzikic", position: "POR", club: "Slaven Belupo" },
  { name: "Sead Kolasinac", position: "DEF", club: "Atalanta" },
  { name: "Amar Dedic", position: "DEF", club: "Benfica" },
  { name: "Nihad Mujakic", position: "DEF", club: "Gaziantep" },
  { name: "Nikola Katic", position: "DEF", club: "Schalke 04" },
  { name: "Tarik Muharemovic", position: "DEF", club: "Sassuolo" },
  { name: "Stjepan Radeljic", position: "DEF", club: "Rijeka" },
  { name: "Dennis Hadzikadunic", position: "DEF", club: "Sampdoria" },
  { name: "Nidal Celik", position: "DEF", club: "Lens" },
  { name: "Amir Hadziahmetovic", position: "MED", club: "Hull City" },
  { name: "Ivan Sunjic", position: "MED", club: "Pafos" },
  { name: "Ivan Basic", position: "MED", club: "Astana" },
  { name: "Dzenis Burnic", position: "MED", club: "Karlsruher SC" },
  { name: "Ermin Mahmic", position: "MED", club: "Slovan Liberec" },
  { name: "Benjamin Tahirovic", position: "MED", club: "Brondby" },
  { name: "Amar Memic", position: "MED", club: "Viktoria Plzen" },
  { name: "Armin Gigovic", position: "MED", club: "Young Boys" },
  { name: "Kerim Alajbegovic", position: "MED", club: "RB Salzburg" },
  { name: "Esmir Bajraktarevic", position: "MED", club: "PSV Eindhoven" },
  { name: "Ermedin Demirovic", position: "DEL", club: "VfB Stuttgart" },
  { name: "Jovo Lukic", position: "DEL", club: "Universitatea Cluj" },
  { name: "Samed Bazdar", position: "DEL", club: "Jagiellonia Bialystok" },
  { name: "Haris Tabakovic", position: "DEL", club: "Borussia Moenchengladbach" },
  { name: "Edin Dzeko", position: "DEL", club: "Schalke 04" },
];

// === BRASIL ===
const BRA: RawPlayer[] = [
  { name: "Alisson", position: "POR", club: "Liverpool" },
  { name: "Ederson", position: "POR", club: "Fenerbahçe" },
  { name: "Weverton", position: "POR", club: "Grêmio" },
  { name: "Wesley", position: "DEF", club: "Roma" },
  { name: "Douglas Santos", position: "DEF", club: "Zenit" },
  { name: "Alex Sandro", position: "DEF", club: "Flamengo" },
  { name: "Gabriel Magalhães", position: "DEF", club: "Arsenal" },
  { name: "Marquinhos", position: "DEF", club: "PSG" },
  { name: "Danilo", position: "DEF", club: "Flamengo" },
  { name: "Bremer", position: "DEF", club: "Juventus" },
  { name: "Ibañez", position: "DEF", club: "Al-Ahli" },
  { name: "Léo Pereira", position: "DEF", club: "Flamengo" },
  { name: "Bruno Guimarães", position: "MED", club: "Newcastle" },
  { name: "Casemiro", position: "MED", club: "Manchester United" },
  { name: "Danilo Santos", position: "MED", club: "Botafogo" },
  { name: "Fabinho", position: "MED", club: "Al-Ittihad" },
  { name: "Lucas Paquetá", position: "MED", club: "Flamengo" },
  { name: "Raphinha", position: "DEL", club: "Barcelona" },
  { name: "Neymar", position: "DEL", club: "Santos" },
  { name: "Vinícius Júnior", position: "DEL", club: "Real Madrid" },
  { name: "Luiz Henrique", position: "DEL", club: "Zenit" },
  { name: "Matheus Cunha", position: "DEL", club: "Manchester United" },
  { name: "Gabriel Martinelli", position: "DEL", club: "Arsenal" },
  { name: "Igor Thiago", position: "DEL", club: "Brentford" },
  { name: "Endrick", position: "DEL", club: "Lyon" },
  { name: "Rayan", position: "DEL", club: "Bournemouth" },
];

// === CABO VERDE ===
const CPV: RawPlayer[] = [
  { name: 'Josimar Dias "Vozinha"', position: "POR", club: "Chaves" },
  { name: "Márcio da Rosa", position: "POR", club: "Montana" },
  { name: "Carlos Santos", position: "POR", club: "San Diego" },
  { name: "Steven Moreira", position: "DEF", club: "Columbus Crew" },
  { name: "Wagner Pina", position: "DEF", club: "Trabzonspor" },
  { name: "João Paulo Fernandes", position: "DEF", club: "FCSB" },
  { name: "Sidny Lopes Cabral", position: "DEF", club: "Benfica" },
  { name: "Logan Costa", position: "DEF", club: "Villarreal" },
  { name: 'Roberto Lopes "Pico"', position: "DEF", club: "Shamrock Rovers" },
  { name: "Kelvin Pires", position: "DEF", club: "SJK" },
  { name: 'Ianique Tavares "Stopira"', position: "DEF", club: "Torreense" },
  { name: 'Edilson Borges "Diney"', position: "DEF", club: "Al Bataeh" },
  { name: "Jamiro Monteiro", position: "MED", club: "PEC Zwolle" },
  { name: "Telmo Arcanjo", position: "MED", club: "Vitória de Guimarães" },
  { name: "Yannick Semedo", position: "MED", club: "Farense" },
  { name: "Laros Duarte", position: "MED", club: "Puskás Akadémia" },
  { name: "Deroy Duarte", position: "MED", club: "Ludogorets Razgrad" },
  { name: "Kevin Pina", position: "MED", club: "Krasnodar" },
  { name: "Gilson Benchimol", position: "DEL", club: "Akron Tolyatti" },
  { name: "Jovane Cabral", position: "DEL", club: "Estrela da Amadora" },
  { name: "Nuno da Costa", position: "DEL", club: "Basaksehir FK" },
  { name: "Dailon Livramento", position: "DEL", club: "Casa Pia AC" },
  { name: "Ryan Mendes", position: "DEL", club: "Igdir" },
  { name: "Garry Rodrigues", position: "DEL", club: "Apollon Limassol" },
  { name: "Willy Semedo", position: "DEL", club: "Omonia Nicosia" },
  { name: "Helio Varela", position: "DEL", club: "Maccabi Tel Aviv" },
];

// === CANADÁ ===
const CAN: RawPlayer[] = [
  { name: "Dayne St. Clair", position: "POR", club: "Inter Miami" },
  { name: "Maxime Crépeau", position: "POR", club: "Orlando City" },
  { name: "Owen Goodman", position: "POR", club: "Crystal Palace" },
  { name: "Alistair Johnston", position: "DEF", club: "Celtic" },
  { name: "Derek Cornelius", position: "DEF", club: "Marseille" },
  { name: "Richie Laryea", position: "DEF", club: "Toronto FC" },
  { name: "Niko Sigur", position: "DEF", club: "Hajduk Split" },
  { name: "Joel Waterman", position: "DEF", club: "Chicago Fire" },
  { name: "Luc De Fougerolles", position: "DEF", club: "Fulham" },
  { name: "Moïse Bombito", position: "DEF", club: "Nice" },
  { name: "Alphonso Davies", position: "DEF", club: "Bayern Munich" },
  { name: "Alfie Jones", position: "DEF", club: "Middlesbrough" },
  { name: "Stephen Eustáquio", position: "MED", club: "Porto" },
  { name: "Ismaël Koné", position: "MED", club: "Sassuolo Calcio" },
  { name: "Tajon Buchanan", position: "MED", club: "Villarreal" },
  { name: "Mathieu Choinière", position: "MED", club: "Los Angeles FC" },
  { name: "Ali Ahmed", position: "MED", club: "Norwich City" },
  { name: "Nathan Saliba", position: "MED", club: "Anderlecht" },
  { name: "Liam Millar", position: "MED", club: "Hull City" },
  { name: "Marcelo Flores", position: "MED", club: "Tigres UANL" },
  { name: "Jacob Shaffelburg", position: "MED", club: "Toronto FC" },
  { name: "Jonathan Osorio", position: "MED", club: "Toronto FC" },
  { name: "Jonathan David", position: "DEL", club: "Juventus" },
  { name: "Cyle Larin", position: "DEL", club: "Southampton" },
  { name: "Tani Oluwaseyi", position: "DEL", club: "Villarreal" },
  { name: "Promise David", position: "DEL", club: "Royale Union Saint-Gilloise" },
];

// === COLOMBIA ===
const COL: RawPlayer[] = [
  { name: "Álvaro Montero", position: "POR", club: "Millonarios" },
  { name: "Camilo Vargas", position: "POR", club: "Atlas" },
  { name: "David Ospina", position: "POR", club: "Atlético Nacional" },
  { name: "Daniel Muñoz", position: "DEF", club: "Crystal Palace" },
  { name: "Santiago Arias", position: "DEF", club: "Bahia" },
  { name: "Davinson Sánchez", position: "DEF", club: "Galatasaray" },
  { name: "Jhon Lucumí", position: "DEF", club: "Bologna" },
  { name: "Yerry Mina", position: "DEF", club: "Cagliari" },
  { name: "Willer Ditta", position: "DEF", club: "Cruz Azul" },
  { name: "Deiver Machado", position: "DEF", club: "Lens" },
  { name: "Johan Mojica", position: "DEF", club: "Mallorca" },
  { name: "Gustavo Puerta", position: "MED", club: "Bayer Leverkusen" },
  { name: "James Rodríguez", position: "MED", club: "São Paulo" },
  { name: "Jefferson Lerma", position: "MED", club: "Crystal Palace" },
  { name: "Jhon Arias", position: "MED", club: "Fluminense" },
  { name: "Jorge Carrascal", position: "MED", club: "Dinamo Moscow" },
  { name: "Juan Fernando Quintero", position: "MED", club: "Racing Club" },
  { name: "Richard Ríos", position: "MED", club: "Palmeiras" },
  { name: "Kevin Castaño", position: "MED", club: "Krasnodar" },
  { name: "Jaminton Campaz", position: "MED", club: "Rosario Central" },
  { name: "Juan Camilo Portilla", position: "MED", club: "Talleres" },
  { name: "Luis Díaz", position: "DEL", club: "Liverpool" },
  { name: "Luis Suárez", position: "DEL", club: "Almería" },
  { name: "Jhon Córdoba", position: "DEL", club: "Krasnodar" },
  { name: "Carlos Andrés Gómez", position: "DEL", club: "Real Salt Lake" },
  { name: "Juan Camilo Hernández", position: "DEL", club: "Columbus Crew" },
];

// === COREA DEL SUR ===
const KOR: RawPlayer[] = [
  { name: "Jo Hyeon-woo", position: "POR", club: "Ulsan" },
  { name: "Kim Seung-gyu", position: "POR", club: "FC Tokyo" },
  { name: "Song Bum-keun", position: "POR", club: "Jeonbuk" },
  { name: "Kim Moon-hwan", position: "DEF", club: "Daejeon" },
  { name: "Kim Min-jae", position: "DEF", club: "Bayern Munich" },
  { name: "Kim Tae-hyon", position: "DEF", club: "Kashima Antlers" },
  { name: "Park Jin-seob", position: "DEF", club: "Zhejiang" },
  { name: "Seol Young-woo", position: "DEF", club: "Red Star Belgrade" },
  { name: "Jens Castrop", position: "DEF", club: "Borussia Monchengladbach" },
  { name: "Lee Ki-hyuk", position: "DEF", club: "Gangwon" },
  { name: "Lee Tae-seok", position: "DEF", club: "Austria Wien" },
  { name: "Lee Han-beom", position: "DEF", club: "Midtjylland" },
  { name: "Cho Yu-min", position: "DEF", club: "Sharjah" },
  { name: "Kim Jin-gyu", position: "MED", club: "Jeonbuk" },
  { name: "Bae Jun-ho", position: "MED", club: "Stoke City" },
  { name: "Paik Seung-ho", position: "MED", club: "Birmingham" },
  { name: "Yang Hyun-jun", position: "MED", club: "Celtic" },
  { name: "Eom Ji-sung", position: "MED", club: "Swansea" },
  { name: "Lee Kang-in", position: "MED", club: "Paris St-Germain" },
  { name: "Lee Dong-gyeong", position: "MED", club: "Ulsan" },
  { name: "Lee Jae-sung", position: "MED", club: "Mainz" },
  { name: "Hwang In-beom", position: "MED", club: "Feyenoord" },
  { name: "Hwang Hee-chan", position: "DEL", club: "Wolves" },
  { name: "Son Heung-min", position: "DEL", club: "LAFC" },
  { name: "Oh Hyeon-gyu", position: "DEL", club: "Besiktas" },
  { name: "Cho Gue-sung", position: "DEL", club: "Midtjylland" },
];

// === COSTA DE MARFIL ===
const CIV: RawPlayer[] = [
  { name: "Yahia Fofana", position: "POR", club: "Çaykur Rizespor" },
  { name: "Mohamed Koné", position: "POR", club: "Charleroi" },
  { name: "Alban Lafont", position: "POR", club: "Panathinaikos" },
  { name: "Emmanuel Agbadou", position: "DEF", club: "Beşiktaş" },
  { name: "Christopher Opéri", position: "DEF", club: "İstanbul Başakşehir" },
  { name: "Ousmane Diomande", position: "DEF", club: "Sporting CP" },
  { name: "Guela Doué", position: "DEF", club: "Strasbourg" },
  { name: "Ghislain Konan", position: "DEF", club: "Gil Vicente" },
  { name: "Odilon Kossounou", position: "DEF", club: "Atalanta BC" },
  { name: "Evan Ndicka", position: "DEF", club: "AS Roma" },
  { name: "Wilfried Singo", position: "DEF", club: "Galatasaray" },
  { name: "Seko Fofana", position: "MED", club: "Porto" },
  { name: "Parfait Guiagon", position: "MED", club: "Charleroi" },
  { name: "Christ Inao Oulaï", position: "MED", club: "Trabzonspor" },
  { name: "Franck Kessié", position: "MED", club: "Al-Ahli" },
  { name: "Ibrahim Sangaré", position: "MED", club: "Nottingham Forest" },
  { name: "Jean-Michaël Seri", position: "MED", club: "Maribor" },
  { name: "Simon Adingra", position: "DEL", club: "Monaco" },
  { name: "Ange-Yoan Bonny", position: "DEL", club: "Inter Milan" },
  { name: "Amad Diallo", position: "DEL", club: "Manchester United" },
  { name: "Oumar Diakité", position: "DEL", club: "Cercle Brugge" },
  { name: "Yan Diomande", position: "DEL", club: "RB Leipzig" },
  { name: "Evann Guessand", position: "DEL", club: "Crystal Palace" },
  { name: "Nicolas Pépé", position: "DEL", club: "Villarreal" },
  { name: "Bazoumana Touré", position: "DEL", club: "TSG Hoffenheim" },
  { name: "Elye Wahi", position: "DEL", club: "OGC Nice" },
];

// === CHEQUIA ===
const CZE: RawPlayer[] = [
  { name: "Matěj Kovář", position: "POR", club: "PSV Eindhoven" },
  { name: "Jindřich Staněk", position: "POR", club: "Slavia Prague" },
  { name: "Lukáš Horníček", position: "POR", club: "Braga" },
  { name: "Vladimír Coufal", position: "DEF", club: "TSG Hoffenheim" },
  { name: "Tomáš Holeš", position: "DEF", club: "Slavia Prague" },
  { name: "Ladislav Krejčí", position: "DEF", club: "Wolves" },
  { name: "David Zima", position: "DEF", club: "Slavia Prague" },
  { name: "Jaroslav Zelený", position: "DEF", club: "Sparta Prague" },
  { name: "David Jurásek", position: "DEF", club: "Slavia Prague" },
  { name: "David Douděra", position: "DEF", club: "Slavia Prague" },
  { name: "Robin Hranáč", position: "DEF", club: "TSG Hoffenheim" },
  { name: "Štěpán Chaloupek", position: "DEF", club: "Slavia Prague" },
  { name: "Tomáš Souček", position: "MED", club: "West Ham" },
  { name: "Vladimír Darida", position: "MED", club: "Hradec Králové" },
  { name: "Lukáš Provod", position: "MED", club: "Slavia Prague" },
  { name: "Michal Sadílek", position: "MED", club: "Slavia Prague" },
  { name: "Pavel Šulc", position: "MED", club: "Olympique Lyonnais" },
  { name: "Lukáš Červ", position: "MED", club: "Viktoria Plzeň" },
  { name: "Hugo Sochůrek", position: "MED", club: "Sparta Prague" },
  { name: "Alexandr Sojka", position: "MED", club: "Viktoria Plzeň" },
  { name: "Denis Višinský", position: "MED", club: "Viktoria Plzeň" },
  { name: "Patrik Schick", position: "DEL", club: "Bayer Leverkusen" },
  { name: "Adam Hložek", position: "DEL", club: "TSG Hoffenheim" },
  { name: "Jan Kuchta", position: "DEL", club: "Sparta Prague" },
  { name: "Mojmír Chytil", position: "DEL", club: "Slavia Prague" },
  { name: "Tomáš Chorý", position: "DEL", club: "Slavia Prague" },
];

// === CROACIA ===
const CRO: RawPlayer[] = [
  { name: "Dominik Livaković", position: "POR", club: "Dinamo Zagreb" },
  { name: "Dominik Kotarski", position: "POR", club: "København" },
  { name: "Ivor Pandur", position: "POR", club: "Hull City" },
  { name: "Joško Gvardiol", position: "DEF", club: "Manchester City" },
  { name: "Duje Ćaleta-Car", position: "DEF", club: "Real Sociedad" },
  { name: "Josip Šutalo", position: "DEF", club: "Ajax" },
  { name: "Josip Stanišić", position: "DEF", club: "Bayern München" },
  { name: "Marin Pongračić", position: "DEF", club: "Fiorentina" },
  { name: "Martin Erlić", position: "DEF", club: "Midtjylland" },
  { name: "Luka Vušković", position: "DEF", club: "Hamburger SV" },
  { name: "Luka Modrić", position: "MED", club: "Real Madrid" },
  { name: "Mateo Kovačić", position: "MED", club: "Manchester City" },
  { name: "Mario Pašalić", position: "MED", club: "Atalanta" },
  { name: "Nikola Vlašić", position: "MED", club: "Torino" },
  { name: "Luka Sučić", position: "MED", club: "Real Sociedad" },
  { name: "Martin Baturina", position: "MED", club: "Como" },
  { name: "Kristijan Jakić", position: "MED", club: "Augsburg" },
  { name: "Petar Sučić", position: "MED", club: "Internazionale" },
  { name: "Nikola Moro", position: "MED", club: "Bologna" },
  { name: "Toni Fruk", position: "MED", club: "Rijeka" },
  { name: "Ivan Perišić", position: "DEL", club: "PSV Eindhoven" },
  { name: "Andrej Kramarić", position: "DEL", club: "Hoffenheim" },
  { name: "Ante Budimir", position: "DEL", club: "Osasuna" },
  { name: "Marco Pašalić", position: "DEL", club: "Orlando City" },
  { name: "Petar Musa", position: "DEL", club: "Dallas" },
  { name: "Igor Matanović", position: "DEL", club: "Freiburg" },
];

// === CURAZAO ===
const CUW: RawPlayer[] = [
  { name: "Eloy Room", position: "POR", club: "Miami FC" },
  { name: "Trevor Dorrnbusch", position: "POR", club: "VVV-Venlo" },
  { name: "Tyrick Bodak", position: "POR", club: "Telstar" },
  { name: "Jurien Gaari", position: "DEF", club: "Abha" },
  { name: "Roshon van Eijma", position: "DEF", club: "RKC Waalwijk" },
  { name: "Sherel Floranus", position: "DEF", club: "PEC Zwolle" },
  { name: "Joshua Brenet", position: "DEF", club: "Kayserispor" },
  { name: "Shurandy Sambo", position: "DEF", club: "Sparta Rotterdam" },
  { name: "Armando Obispo", position: "DEF", club: "PSV" },
  { name: "Riechedly Bazoer", position: "DEF", club: "Konyaspor" },
  { name: "Deveron Fonville", position: "DEF", club: "NEC" },
  { name: "Leandro Bacuna", position: "MED", club: "Igdir" },
  { name: "Juninho Bacuna", position: "MED", club: "Volendam" },
  { name: "Godfried Roemeratoe", position: "MED", club: "RKC Waalwijk" },
  { name: "Kevin Felida", position: "MED", club: "Den Bosch" },
  { name: "Livano Comenencia", position: "MED", club: "Zurich" },
  { name: "Ar'jany Martha", position: "MED", club: "Rotherham United" },
  { name: "Tyrese Noslin", position: "MED", club: "Telstar" },
  { name: "Kenji Gorré", position: "DEL", club: "Maccabi Haifa" },
  { name: "Brandley Kuwas", position: "DEL", club: "Volendam" },
  { name: "Gervane Kastaneer", position: "DEL", club: "Terengganu" },
  { name: "Jeremy Antonisse", position: "DEL", club: "Kifisia" },
  { name: "Jearl Margaritha", position: "DEL", club: "Beveren" },
  { name: "Jurgen Locadia", position: "DEL", club: "Miami FC" },
  { name: "Sontje Hansen", position: "DEL", club: "Middlesbrough" },
  { name: "Tahith Chong", position: "DEL", club: "Sheffield United" },
];

// === ECUADOR ===
const ECU: RawPlayer[] = [
  { name: "Hernán Galíndez", position: "POR", club: "Huracán" },
  { name: "Moisés Ramírez", position: "POR", club: "AE Kifisias" },
  { name: "Gonzalo Valle", position: "POR", club: "LDU Quito" },
  { name: "Willian Pacho", position: "DEF", club: "PSG" },
  { name: "Piero Hincapié", position: "DEF", club: "Arsenal" },
  { name: "Joel Ordóñez", position: "DEF", club: "Club Brugge" },
  { name: "Félix Torres", position: "DEF", club: "Internacional" },
  { name: "Pervis Estupiñán", position: "DEF", club: "AC Milan" },
  { name: "Ángelo Preciado", position: "DEF", club: "Atlético Mineiro" },
  { name: "Jackson Porozo", position: "DEF", club: "Club Tijuana" },
  { name: "Moisés Caicedo", position: "MED", club: "Chelsea" },
  { name: "Jordy Alcívar", position: "MED", club: "Independiente del Valle" },
  { name: "Denil Castillo", position: "MED", club: "Midtjylland" },
  { name: "Alan Franco", position: "MED", club: "Atlético Mineiro" },
  { name: "Pedro Vite", position: "MED", club: "Pumas UNAM" },
  { name: "Kendry Páez", position: "MED", club: "River Plate" },
  { name: "Yaimar Medina", position: "MED", club: "KRC Genk" },
  { name: "Kevin Rodríguez", position: "DEL", club: "Union Saint-Gilloise" },
  { name: "Anthony Valencia", position: "DEL", club: "Royal Antwerp" },
  { name: "Enner Valencia", position: "DEL", club: "Pachuca" },
  { name: "Jordy Caicedo", position: "DEL", club: "Huracán" },
  { name: "Jeremy Arévalo", position: "DEL", club: "Stuttgart" },
  { name: "Gonzalo Plata", position: "DEL", club: "Flamengo" },
  { name: "Alan Minda", position: "DEL", club: "Atlético Mineiro" },
  { name: "John Yeboah", position: "DEL", club: "Venezia" },
  { name: "Nilson Angulo", position: "DEL", club: "Sunderland" },
];

// === ESCOCIA ===
const SCO: RawPlayer[] = [
  { name: "Craig Gordon", position: "POR", club: "Hearts" },
  { name: "Angus Gunn", position: "POR", club: "Nottingham Forest" },
  { name: "Liam Kelly", position: "POR", club: "Rangers" },
  { name: "Grant Hanley", position: "DEF", club: "Hibernian" },
  { name: "Jack Hendry", position: "DEF", club: "Al-Ettifaq" },
  { name: "Aaron Hickey", position: "DEF", club: "Brentford" },
  { name: "Dom Hyam", position: "DEF", club: "Wrexham" },
  { name: "Scott McKenna", position: "DEF", club: "Dinamo Zagreb" },
  { name: "Nathan Patterson", position: "DEF", club: "Everton" },
  { name: "Anthony Ralston", position: "DEF", club: "Celtic" },
  { name: "Andy Robertson", position: "DEF", club: "Liverpool" },
  { name: "John Souttar", position: "DEF", club: "Rangers" },
  { name: "Kieran Tierney", position: "DEF", club: "Celtic" },
  { name: "Ryan Christie", position: "MED", club: "Bournemouth" },
  { name: "Findlay Curtis", position: "MED", club: "Rangers" },
  { name: "Lewis Ferguson", position: "MED", club: "Bologna" },
  { name: "Ben Gannon-Doak", position: "MED", club: "Bournemouth" },
  { name: "Billy Gilmour", position: "MED", club: "Napoli" },
  { name: "John McGinn", position: "MED", club: "Aston Villa" },
  { name: "Kenny McLean", position: "MED", club: "Norwich City" },
  { name: "Scott McTominay", position: "MED", club: "Napoli" },
  { name: "Che Adams", position: "DEL", club: "Torino" },
  { name: "Lyndon Dykes", position: "DEL", club: "Charlton Athletic" },
  { name: "George Hirst", position: "DEL", club: "Ipswich Town" },
  { name: "Lawrence Shankland", position: "DEL", club: "Hearts" },
  { name: "Ross Stewart", position: "DEL", club: "Southampton" },
];

// === ESPAÑA ===
const ESP: RawPlayer[] = [
  { name: "Unai Simón", position: "POR", club: "Athletic Club" },
  { name: "David Raya", position: "POR", club: "Arsenal" },
  { name: "Joan García", position: "POR", club: "Barcelona" },
  { name: "Pedro Porro", position: "DEF", club: "Tottenham Hotspur" },
  { name: "Marcos Llorente", position: "DEF", club: "Atlético Madrid" },
  { name: "Aymeric Laporte", position: "DEF", club: "Athletic Club" },
  { name: "Pau Cubarsí", position: "DEF", club: "Barcelona" },
  { name: "Marc Pubill", position: "DEF", club: "Atlético Madrid" },
  { name: "Eric García", position: "DEF", club: "Barcelona" },
  { name: "Marc Cucurella", position: "DEF", club: "Chelsea" },
  { name: "Alejandro Grimaldo", position: "DEF", club: "Bayer Leverkusen" },
  { name: "Rodrigo Hernández (Rodri)", position: "MED", club: "Manchester City" },
  { name: "Martín Zubimendi", position: "MED", club: "Arsenal" },
  { name: "Pedri González", position: "MED", club: "Barcelona" },
  { name: "Fabián Ruiz", position: "MED", club: "PSG" },
  { name: "Mikel Merino", position: "MED", club: "Arsenal" },
  { name: "Pablo Páez 'Gavi'", position: "MED", club: "Barcelona" },
  { name: "Álex Baena", position: "MED", club: "Atlético Madrid" },
  { name: "Mikel Oyarzabal", position: "DEL", club: "Real Sociedad" },
  { name: "Lamine Yamal", position: "DEL", club: "Barcelona" },
  { name: "Ferran Torres", position: "DEL", club: "Barcelona" },
  { name: "Borja Iglesias", position: "DEL", club: "Celta Vigo" },
  { name: "Dani Olmo", position: "DEL", club: "Barcelona" },
  { name: "Víctor Múñoz", position: "DEL", club: "Osasuna" },
  { name: "Nico Williams", position: "DEL", club: "Athletic Club" },
  { name: "Yéremy Pino", position: "DEL", club: "Crystal Palace" },
];

// === ESTADOS UNIDOS ===
const USA: RawPlayer[] = [
  { name: "Chris Brady", position: "POR", club: "Chicago Fire" },
  { name: "Matt Freese", position: "POR", club: "New York City FC" },
  { name: "Matt Turner", position: "POR", club: "New England Revolution" },
  { name: "Max Arfsten", position: "DEF", club: "Columbus Crew" },
  { name: "Sergiño Dest", position: "DEF", club: "PSV" },
  { name: "Alex Freeman", position: "DEF", club: "Villarreal" },
  { name: "Mark McKenzie", position: "DEF", club: "Toulouse" },
  { name: "Tim Ream", position: "DEF", club: "Charlotte FC" },
  { name: "Chris Richards", position: "DEF", club: "Crystal Palace" },
  { name: "Antonee Robinson", position: "DEF", club: "Fulham" },
  { name: "Miles Robinson", position: "DEF", club: "FC Cincinnati" },
  { name: "Joe Scally", position: "DEF", club: "Borussia Mönchengladbach" },
  { name: "Auston Trusty", position: "DEF", club: "Celtic" },
  { name: "Tyler Adams", position: "MED", club: "AFC Bournemouth" },
  { name: "Sebastian Berhalter", position: "MED", club: "Vancouver Whitecaps" },
  { name: "Weston McKennie", position: "MED", club: "Juventus" },
  { name: "Cristian Roldan", position: "MED", club: "Seattle Sounders" },
  { name: "Gio Reyna", position: "MED", club: "Borussia Mönchengladbach" },
  { name: "Malik Tillman", position: "MED", club: "Bayer Leverkusen" },
  { name: "Folarin Balogun", position: "DEL", club: "AS Monaco" },
  { name: "Ricardo Pepi", position: "DEL", club: "PSV" },
  { name: "Haji Wright", position: "DEL", club: "Coventry City" },
  { name: "Brenden Aaronson", position: "DEL", club: "Leeds United" },
  { name: "Christian Pulisic", position: "DEL", club: "Milan" },
  { name: "Tim Weah", position: "DEL", club: "Marseille" },
  { name: "Alejandro Zendejas", position: "DEL", club: "Club América" },
];

// === FRANCIA ===
const FRA: RawPlayer[] = [
  { name: "Mike Maignan", position: "POR", club: "AC Milan" },
  { name: "Brice Samba", position: "POR", club: "Rennes" },
  { name: "Robin Risser", position: "POR", club: "Lens" },
  { name: "Dayot Upamecano", position: "DEF", club: "Bayern Munich" },
  { name: "William Saliba", position: "DEF", club: "Arsenal" },
  { name: "Lucas Digne", position: "DEF", club: "Aston Villa" },
  { name: "Theo Hernandez", position: "DEF", club: "Al-Hilal" },
  { name: "Lucas Hernandez", position: "DEF", club: "PSG" },
  { name: "Ibrahima Konaté", position: "DEF", club: "Liverpool" },
  { name: "Jules Koundé", position: "DEF", club: "Barcelona" },
  { name: "Malo Gusto", position: "DEF", club: "Chelsea" },
  { name: "Maxence Lacroix", position: "DEF", club: "Crystal Palace" },
  { name: "N'Golo Kanté", position: "MED", club: "Fenerbahce" },
  { name: "Adrien Rabiot", position: "MED", club: "AC Milan" },
  { name: "Manu Koné", position: "MED", club: "Roma" },
  { name: "Aurélien Tchouaméni", position: "MED", club: "Real Madrid" },
  { name: "Warren Zaïre-Emery", position: "MED", club: "PSG" },
  { name: "Maghnes Akliouche", position: "DEL", club: "AS Monaco" },
  { name: "Bradley Barcola", position: "DEL", club: "PSG" },
  { name: "Rayan Cherki", position: "DEL", club: "Lyon" },
  { name: "Ousmane Dembélé", position: "DEL", club: "PSG" },
  { name: "Désiré Doué", position: "DEL", club: "PSG" },
  { name: "Jean-Philippe Mateta", position: "DEL", club: "Crystal Palace" },
  { name: "Kylian Mbappé", position: "DEL", club: "Real Madrid" },
  { name: "Michael Olise", position: "DEL", club: "Bayern Munich" },
  { name: "Marcus Thuram", position: "DEL", club: "Inter Milan" },
];

// === HAITÍ ===
const HAI: RawPlayer[] = [
  { name: "Johnny Placide", position: "POR", club: "Bastia" },
  { name: "Alexandre Pierre", position: "POR", club: "Sochaux" },
  { name: "Josué Duverger", position: "POR", club: "Cosmos Koblenz" },
  { name: "Ricardo Adé", position: "DEF", club: "LDU Quito" },
  { name: "Carlens Arcus", position: "DEF", club: "Angers" },
  { name: "Martin Experience", position: "DEF", club: "Nancy" },
  { name: "Jean-Kevin Duverné", position: "DEF", club: "Gent" },
  { name: "Duke Lacroix", position: "DEF", club: "Colorado Springs Switchbacks" },
  { name: "Wilguens Paugain", position: "DEF", club: "Zulte Waregem" },
  { name: "Hannes Delcroix", position: "DEF", club: "Lugano" },
  { name: "Keeto Thermoncy", position: "DEF", club: "Young Boys" },
  { name: "Leverton Pierre", position: "MED", club: "Vizela" },
  { name: "Danley Jean Jacques", position: "MED", club: "Philadelphia Union" },
  { name: "Carl Sainté", position: "MED", club: "El Paso Locomotive" },
  { name: "Jean-Ricner Bellegarde", position: "MED", club: "Wolves" },
  { name: "Woodensky Pierre", position: "MED", club: "Violette" },
  { name: "Dominique Simon", position: "MED", club: "Tatran Presov" },
  { name: "Duckens Nazon", position: "DEL", club: "Esteghlal" },
  { name: "Frantzy Perrot", position: "DEL", club: "Çaykur Rizespor" },
  { name: "Derrick Etienne Jr.", position: "DEL", club: "Toronto FC" },
  { name: "Louicius Deedson", position: "DEL", club: "FC Dallas" },
  { name: "Ruben Providence", position: "DEL", club: "Almere City" },
  { name: "Josué Casimir", position: "DEL", club: "Auxerre" },
  { name: "Yassin Fortuné", position: "DEL", club: "Vizela" },
  { name: "Wilson Isidor", position: "DEL", club: "Sunderland" },
  { name: "Lenny Joseph", position: "DEL", club: "Ferencvaros" },
];

// === INGLATERRA ===
const ING: RawPlayer[] = [
  { name: "Dean Henderson", position: "POR", club: "Crystal Palace" },
  { name: "Jordan Pickford", position: "POR", club: "Everton" },
  { name: "James Trafford", position: "POR", club: "Manchester City" },
  { name: "Dan Burn", position: "DEF", club: "Newcastle United" },
  { name: "Marc Guehi", position: "DEF", club: "Crystal Palace" },
  { name: "Reece James", position: "DEF", club: "Chelsea" },
  { name: "Ezri Konsa", position: "DEF", club: "Aston Villa" },
  { name: "Tino Livramento", position: "DEF", club: "Newcastle United" },
  { name: "Nico O'Reilly", position: "DEF", club: "Manchester City" },
  { name: "Jarell Quansah", position: "DEF", club: "Liverpool" },
  { name: "Djed Spence", position: "DEF", club: "Tottenham Hotspur" },
  { name: "John Stones", position: "DEF", club: "Manchester City" },
  { name: "Elliot Anderson", position: "MED", club: "Nottingham Forest" },
  { name: "Jude Bellingham", position: "MED", club: "Real Madrid" },
  { name: "Eberechi Eze", position: "MED", club: "Arsenal" },
  { name: "Jordan Henderson", position: "MED", club: "Brentford" },
  { name: "Kobbie Mainoo", position: "MED", club: "Manchester United" },
  { name: "Declan Rice", position: "MED", club: "Arsenal" },
  { name: "Morgan Rogers", position: "MED", club: "Aston Villa" },
  { name: "Anthony Gordon", position: "DEL", club: "Barcelona" },
  { name: "Harry Kane", position: "DEL", club: "Bayern Munich" },
  { name: "Noni Madueke", position: "DEL", club: "Arsenal" },
  { name: "Marcus Rashford", position: "DEL", club: "Barcelona" },
  { name: "Bukayo Saka", position: "DEL", club: "Arsenal" },
  { name: "Ivan Toney", position: "DEL", club: "Al-Ahli" },
  { name: "Ollie Watkins", position: "DEL", club: "Aston Villa" },
];

// === JAPÓN ===
const JPN: RawPlayer[] = [
  { name: "Tomoki Hayakawa", position: "POR", club: "Kashima Antlers" },
  { name: "Keisuke Osako", position: "POR", club: "Sanfrecce Hiroshima" },
  { name: "Zion Suzuki", position: "POR", club: "Parma" },
  { name: "Ko Itakura", position: "DEF", club: "Ajax" },
  { name: "Hiroki Ito", position: "DEF", club: "Bayern Munich" },
  { name: "Yuto Nagatomo", position: "DEF", club: "FC Tokyo" },
  { name: "Ayumu Seko", position: "DEF", club: "Le Havre" },
  { name: "Yukinari Sugawara", position: "DEF", club: "Werder Bremen" },
  { name: "Junnosuke Suzuki", position: "DEF", club: "København" },
  { name: "Shogo Taniguchi", position: "DEF", club: "Sint-Truiden" },
  { name: "Takehiro Tomiyasu", position: "DEF", club: "Ajax" },
  { name: "Tsuyoshi Watanabe", position: "DEF", club: "Feyenoord" },
  { name: "Ritsu Doan", position: "MED", club: "Eintracht Frankfurt" },
  { name: "Wataru Endo", position: "MED", club: "Liverpool" },
  { name: "Junya Ito", position: "MED", club: "Genk" },
  { name: "Daichi Kamada", position: "MED", club: "Crystal Palace" },
  { name: "Takefusa Kubo", position: "MED", club: "Real Sociedad" },
  { name: "Keito Nakamura", position: "MED", club: "Reims" },
  { name: "Kaishu Sano", position: "MED", club: "Mainz" },
  { name: "Ao Tanaka", position: "MED", club: "Leeds United" },
  { name: "Keisuke Goto", position: "DEL", club: "Sint-Truiden" },
  { name: "Daizen Maeda", position: "DEL", club: "Celtic" },
  { name: "Koki Ogawa", position: "DEL", club: "Nijmegen" },
  { name: "Kento Shiogai", position: "DEL", club: "Wolfsburg" },
  { name: "Yuito Suzuki", position: "DEL", club: "Freiburg" },
  { name: "Ayase Ueda", position: "DEL", club: "Feyenoord" },
];

// === MARRUECOS ===
const MAR: RawPlayer[] = [
  { name: "Yassine Bounou", position: "POR", club: "Al Hilal" },
  { name: "Munir El Kajoui", position: "POR", club: "RS Berkane" },
  { name: "Ahmed Reda Tagnaouti", position: "POR", club: "AS FAR" },
  { name: "Noussair Mazraoui", position: "DEF", club: "Manchester United" },
  { name: "Anass Salah-Eddine", position: "DEF", club: "PSV Eindhoven" },
  { name: "Youssef Belammari", position: "DEF", club: "Al Ahly" },
  { name: "Nayef Aguerd", position: "DEF", club: "Olympique de Marseille" },
  { name: "Chadi Riad", position: "DEF", club: "Crystal Palace" },
  { name: "Issa Diop", position: "DEF", club: "Fulham" },
  { name: "Redouane Halhal", position: "DEF", club: "Mechelen" },
  { name: "Achraf Hakimi", position: "DEF", club: "PSG" },
  { name: "Zakaria El Ouahdi", position: "DEF", club: "Genk" },
  { name: "Samir El Mourabet", position: "MED", club: "Strasbourg" },
  { name: "Ayyoub Bouaddi", position: "MED", club: "Lille" },
  { name: "Neil El Aynaoui", position: "MED", club: "AS Roma" },
  { name: "Sofyan Amrabat", position: "MED", club: "Real Betis" },
  { name: "Azzedine Ounahi", position: "MED", club: "Girona" },
  { name: "Bilal El Khannouss", position: "MED", club: "Stuttgart" },
  { name: "Ismael Saibari", position: "MED", club: "PSV Eindhoven" },
  { name: "Abdessamad Ezzalzouli", position: "DEL", club: "Real Betis" },
  { name: "Chemsdine Talbi", position: "DEL", club: "Sunderland" },
  { name: "Soufiane Rahimi", position: "DEL", club: "Al Ain" },
  { name: "Ayoub El Kaabi", position: "DEL", club: "Olympiacos" },
  { name: "Brahim Díaz", position: "DEL", club: "Real Madrid" },
  { name: "Gessime Yassine", position: "DEL", club: "Strasbourg" },
  { name: "Ayoube Amaïmouni", position: "DEL", club: "Eintracht Frankfurt" },
];

// === MÉXICO ===
const MEX: RawPlayer[] = [
  { name: "Raúl Rangel", position: "POR", club: "Guadalajara" },
  { name: "Guillermo Ochoa", position: "POR", club: "AEL Limassol" },
  { name: "Carlos Acevedo", position: "POR", club: "Santos Laguna" },
  { name: "Jorge Sánchez", position: "DEF", club: "PAOK" },
  { name: "Israel Reyes", position: "DEF", club: "Club América" },
  { name: "César Montes", position: "DEF", club: "Lokomotiv Moscow" },
  { name: "Johan Vásquez", position: "DEF", club: "Genoa" },
  { name: "Jesús Gallardo", position: "DEF", club: "Toluca" },
  { name: "Mateo Chávez", position: "DEF", club: "AZ Alkmaar" },
  { name: "Erik Lira", position: "MED", club: "Cruz Azul" },
  { name: "Orbelín Pineda", position: "MED", club: "AEK Athens" },
  { name: "Álvaro Fidalgo", position: "MED", club: "Real Betis" },
  { name: "Roberto Alvarado", position: "MED", club: "Guadalajara" },
  { name: "Brian Gutiérrez", position: "MED", club: "Guadalajara" },
  { name: "Luis Romo", position: "MED", club: "Guadalajara" },
  { name: "Edson Álvarez", position: "MED", club: "Fenerbahçe" },
  { name: "Obed Vargas", position: "MED", club: "Atlético Madrid" },
  { name: "Gilberto Mora", position: "MED", club: "Tijuana" },
  { name: "Luis Chávez", position: "MED", club: "Dynamo Moscow" },
  { name: "César Huerta", position: "DEL", club: "Anderlecht" },
  { name: "Alexis Vega", position: "DEL", club: "Toluca" },
  { name: "Julián Quiñones", position: "DEL", club: "Al-Qadsiah" },
  { name: "Guillermo Martínez", position: "DEL", club: "UNAM" },
  { name: "Armando González", position: "DEL", club: "Guadalajara" },
  { name: "Santiago Giménez", position: "DEL", club: "AC Milan" },
  { name: "Raúl Jiménez", position: "DEL", club: "Fulham" },
];

// === NORUEGA ===
const NOR: RawPlayer[] = [
  { name: "Ørjan Nyland", position: "POR", club: "Sevilla" },
  { name: "Egil Selvik", position: "POR", club: "Watford" },
  { name: "Sander Tangvik", position: "POR", club: "Hamburger SV" },
  { name: "Julian Ryerson", position: "DEF", club: "Borussia Dortmund" },
  { name: "Marcus Holmgren Pedersen", position: "DEF", club: "Torino" },
  { name: "David Møller Wolfe", position: "DEF", club: "Wolverhampton Wanderers" },
  { name: "Fredrik Bjørkan", position: "DEF", club: "Bodø/Glimt" },
  { name: "Kristoffer Ajer", position: "DEF", club: "Brentford" },
  { name: "Torbjørn Heggelund", position: "DEF", club: "Bologna" },
  { name: "Leo Skiri Østigård", position: "DEF", club: "Genoa" },
  { name: "Sondre Langås", position: "DEF", club: "Derby County" },
  { name: "Henrik Falchener", position: "DEF", club: "Viking" },
  { name: "Martin Ødegaard", position: "MED", club: "Arsenal" },
  { name: "Sander Berge", position: "MED", club: "Fulham" },
  { name: "Fredrik Aursnes", position: "MED", club: "Benfica" },
  { name: "Patrick Berg", position: "MED", club: "Bodø/Glimt" },
  { name: "Kristian Thorstvedt", position: "MED", club: "Sassuolo" },
  { name: "Morten Thorsby", position: "MED", club: "Cremonese" },
  { name: "Thelo Aasgaard", position: "MED", club: "Rangers" },
  { name: "Andreas Schjelderup", position: "MED", club: "Benfica" },
  { name: "Jens Petter Hauge", position: "MED", club: "Bodø/Glimt" },
  { name: "Erling Haaland", position: "DEL", club: "Manchester City" },
  { name: "Alexander Sørloth", position: "DEL", club: "Atlético Madrid" },
  { name: "Jørgen Strand Larsen", position: "DEL", club: "Crystal Palace" },
  { name: "Oscar Bobb", position: "DEL", club: "Fulham" },
  { name: "Antonio Nusa", position: "DEL", club: "RB Leipzig" },
];

// === NUEVA ZELANDA ===
const NZL: RawPlayer[] = [
  { name: "Max Crocombe", position: "POR", club: "Millwall FC" },
  { name: "Alex Paulsen", position: "POR", club: "Lechia Gdańsk" },
  { name: "Michael Woud", position: "POR", club: "Auckland FC" },
  { name: "Tim Payne", position: "DEF", club: "Wellington Phoenix" },
  { name: "Francis De Vries", position: "DEF", club: "Auckland FC" },
  { name: "Tyler Bindon", position: "DEF", club: "Nottingham Forest" },
  { name: "Michael Boxall", position: "DEF", club: "Minnesota United" },
  { name: "Liberato Cacace", position: "DEF", club: "Wrexham AFC" },
  { name: "Nando Pijnaaker", position: "DEF", club: "Auckland FC" },
  { name: "Finn Surman", position: "DEF", club: "Portland Timbers" },
  { name: "Callan Elliot", position: "DEF", club: "Auckland FC" },
  { name: "Tommy Smith", position: "DEF", club: "Braintree Town" },
  { name: "Joe Bell", position: "MED", club: "Viking FK" },
  { name: "Marko Stamenić", position: "MED", club: "Swansea City" },
  { name: "Alex Rufer", position: "MED", club: "Wellington Phoenix" },
  { name: "Ryan Thomas", position: "MED", club: "PEC Zwolle" },
  { name: "Lachlan Bayliss", position: "MED", club: "Newcastle Jets" },
  { name: "Matt Garbett", position: "MED", club: "Peterborough United" },
  { name: "Sarpreet Singh", position: "MED", club: "Wellington Phoenix" },
  { name: "Eli Just", position: "MED", club: "Motherwell FC" },
  { name: "Ben Old", position: "MED", club: "Saint-Étienne" },
  { name: "Callum McCowatt", position: "DEL", club: "Silkeborg" },
  { name: "Kosta Barbarouses", position: "DEL", club: "Western Sydney Wanderers" },
  { name: "Jesse Randall", position: "DEL", club: "Auckland FC" },
  { name: "Ben Waine", position: "DEL", club: "Port Vale" },
  { name: "Chris Wood", position: "DEL", club: "Nottingham Forest" },
];

// === PAÍSES BAJOS ===
const NED: RawPlayer[] = [
  { name: "Mark Flekken", position: "POR", club: "Bayer Leverkusen" },
  { name: "Robin Roefs", position: "POR", club: "Sunderland" },
  { name: "Bart Verbruggen", position: "POR", club: "Brighton" },
  { name: "Nathan Aké", position: "DEF", club: "Manchester City" },
  { name: "Denzel Dumfries", position: "DEF", club: "Inter Milan" },
  { name: "Jorrel Hato", position: "DEF", club: "Chelsea" },
  { name: "Jurriën Timber", position: "DEF", club: "Arsenal" },
  { name: "Jan Paul van Hecke", position: "DEF", club: "Brighton" },
  { name: "Micky van de Ven", position: "DEF", club: "Tottenham Hotspur" },
  { name: "Virgil van Dijk", position: "DEF", club: "Liverpool" },
  { name: "Frenkie de Jong", position: "MED", club: "Barcelona" },
  { name: "Marten de Roon", position: "MED", club: "Atalanta" },
  { name: "Ryan Gravenberch", position: "MED", club: "Liverpool" },
  { name: "Teun Koopmeiners", position: "MED", club: "Juventus" },
  { name: "Tijjani Reijnders", position: "MED", club: "Manchester City" },
  { name: "Guus Til", position: "MED", club: "PSV" },
  { name: "Quinten Timber", position: "MED", club: "Marseille" },
  { name: "Mats Wieffer", position: "MED", club: "Brighton" },
  { name: "Brian Brobbey", position: "DEL", club: "Sunderland" },
  { name: "Memphis Depay", position: "DEL", club: "Corinthians" },
  { name: "Cody Gakpo", position: "DEL", club: "Liverpool" },
  { name: "Justin Kluivert", position: "DEL", club: "Bournemouth" },
  { name: "Noa Lang", position: "DEL", club: "Galatasaray" },
  { name: "Donyell Malen", position: "DEL", club: "Roma" },
  { name: "Crysencio Summerville", position: "DEL", club: "West Ham" },
  { name: "Wout Weghorst", position: "DEL", club: "Ajax" },
];

// === PANAMÁ ===
const PAN: RawPlayer[] = [
  { name: "Orlando Mosquera", position: "POR", club: "Al-Fayha FC" },
  { name: "Luis Mejía", position: "POR", club: "Club Nacional" },
  { name: "César Samudio", position: "POR", club: "CD Marathon" },
  { name: "César Blackman", position: "DEF", club: "Slovan Bratislava" },
  { name: "Jorge Gutiérrez", position: "DEF", club: "Deportivo La Guaira" },
  { name: "Amir Murillo", position: "DEF", club: "Besiktas" },
  { name: "Fidel Escobar", position: "DEF", club: "Deportivo Saprissa" },
  { name: "Andrés Andrade", position: "DEF", club: "LASK" },
  { name: "Edgardo Fariña", position: "DEF", club: "FC Pari Nizhniy Novgorod" },
  { name: "José Córdoba", position: "DEF", club: "Norwich City" },
  { name: "Eric Davis", position: "DEF", club: "CD Plaza Amador" },
  { name: "Jiovani Ramos", position: "DEF", club: "Academia Puerto Cabello" },
  { name: "Roderick Miller", position: "DEF", club: "Turan Tovuz" },
  { name: "Aníbal Godoy", position: "MED", club: "San Diego FC" },
  { name: "Adalberto Carrasquilla", position: "MED", club: "UNAM Pumas" },
  { name: "Carlos Harvey", position: "MED", club: "Minnesota United FC" },
  { name: "Cristian Martínez", position: "MED", club: "Ironi Kiryat Shmona" },
  { name: "José Luis Rodríguez", position: "MED", club: "FC Juarez" },
  { name: "Cesar Yanis", position: "MED", club: "CD Cobresal" },
  { name: "Yoel Bárcenas", position: "MED", club: "Mazatlan FC" },
  { name: "Alberto Quintero", position: "MED", club: "CD Plaza Amador" },
  { name: "Azarías Londoño", position: "MED", club: "CD Universidad Católica" },
  { name: "Ismael Diaz", position: "DEL", club: "Club León" },
  { name: "Cecilio Waterman", position: "DEL", club: "Universidad de Concepción" },
  { name: "Jose Fajardo", position: "DEL", club: "Universidad Católica del Ecuador" },
  { name: "Tomas Rodriguez", position: "DEL", club: "Deportivo Saprissa" },
];

// === RD DEL CONGO ===
const COD: RawPlayer[] = [
  { name: "Lionel Mpasi", position: "POR", club: "Le Havre" },
  { name: "Matthieu Epolo", position: "POR", club: "Standard Liège" },
  { name: "Timothy Fayulu", position: "POR", club: "FC Noah" },
  { name: "Chancel Mbemba", position: "DEF", club: "Lille" },
  { name: "Axel Tuanzebe", position: "DEF", club: "Burnley" },
  { name: "Arthur Masuaku", position: "DEF", club: "Lens" },
  { name: "Gédéon Kalulu", position: "DEF", club: "Aris Limassol" },
  { name: "Joris Kayembe", position: "DEF", club: "Genk" },
  { name: "Aaron Wan-Bissaka", position: "DEF", club: "West Ham United" },
  { name: "Steve Kapuadi", position: "DEF", club: "Widzew Łódź" },
  { name: "Dylan Batubinsika", position: "DEF", club: "AEL" },
  { name: "Rocky Bushiri", position: "DEF", club: "Hibernian" },
  { name: "Noah Sadiki", position: "MED", club: "Sunderland" },
  { name: "Charles Pickel", position: "MED", club: "Espanyol" },
  { name: "Edo Kayembe", position: "MED", club: "Watford" },
  { name: "Samuel Moutoussamy", position: "MED", club: "Atromitos" },
  { name: "Ngal'ayel Mukau", position: "MED", club: "Lille" },
  { name: "Nathanaël Mbuku", position: "MED", club: "Montpellier" },
  { name: "Meschak Elia", position: "MED", club: "Alanyaspor" },
  { name: "Brian Cipenga", position: "MED", club: "Castellón" },
  { name: "Gaël Kakuta", position: "MED", club: "AEL" },
  { name: "Théo Bongonda", position: "DEL", club: "Spartak Moscow" },
  { name: "Simon Banza", position: "DEL", club: "Al Jazira" },
  { name: "Yoane Wissa", position: "DEL", club: "Newcastle United" },
  { name: "Fiston Mayele", position: "DEL", club: "Pyramids FC" },
  { name: "Cédric Bakambu", position: "DEL", club: "Real Betis" },
];

// === SUDÁFRICA ===
const RSA: RawPlayer[] = [
  { name: "Ronwen Williams", position: "POR", club: "Mamelodi Sundowns" },
  { name: "Ricardo Goss", position: "POR", club: "Siwelele FC" },
  { name: "Sipho Chaine", position: "POR", club: "Orlando Pirates" },
  { name: "Khuliso Mudau", position: "DEF", club: "Mamelodi Sundowns" },
  { name: "Aubrey Modiba", position: "DEF", club: "Mamelodi Sundowns" },
  { name: "Khulumani Ndamane", position: "DEF", club: "Mamelodi Sundowns" },
  { name: "Olwethu Makhanya", position: "DEF", club: "Philadelphia Union" },
  { name: "Bradley Cross", position: "DEF", club: "Kaizer Chiefs" },
  { name: "Thabang Matuludi", position: "DEF", club: "Polokwane City" },
  { name: "Nkosinathi Sibisi", position: "DEF", club: "Orlando Pirates" },
  { name: "Kamogelo Sebelebele", position: "DEF", club: "Orlando Pirates" },
  { name: "Ime Okon", position: "DEF", club: "Hannover 96" },
  { name: "Samukele Kabini", position: "DEF", club: "Molde FK" },
  { name: "Mbekezeli Mbokazi", position: "DEF", club: "Chicago Fire" },
  { name: "Teboho Mokoena", position: "MED", club: "Mamelodi Sundowns" },
  { name: "Jayden Adams", position: "MED", club: "Mamelodi Sundowns" },
  { name: "Thalente Mbatha", position: "MED", club: "Orlando Pirates" },
  { name: "Sphephelo Sithole", position: "MED", club: "CD Tondela" },
  { name: "Oswin Apollis", position: "DEL", club: "Orlando Pirates" },
  { name: "Tshepang Moremi", position: "DEL", club: "Orlando Pirates" },
  { name: "Evidence Makgopa", position: "DEL", club: "Orlando Pirates" },
  { name: "Relebohile Mofokeng", position: "DEL", club: "Orlando Pirates" },
  { name: "Lyle Foster", position: "DEL", club: "Burnley" },
  { name: "Iqraam Rayners", position: "DEL", club: "Mamelodi Sundowns" },
  { name: "Themba Zwane", position: "DEL", club: "Mamelodi Sundowns" },
  { name: "Thapelo Maseko", position: "DEL", club: "AEL Limassol" },
];

// === SUECIA ===
const SWE: RawPlayer[] = [
  { name: "Kristoffer Nordfeldt", position: "POR", club: "AIK" },
  { name: "Viktor Johansson", position: "POR", club: "Stoke City" },
  { name: "Jacob Widell Zetterström", position: "POR", club: "Derby County" },
  { name: "Gustaf Lagerbielke", position: "POR", club: "Braga" },
  { name: "Victor Lindelöf", position: "DEF", club: "Aston Villa" },
  { name: "Isak Hien", position: "DEF", club: "Atalanta" },
  { name: "Gabriel Gudmundsson", position: "DEF", club: "Leeds United" },
  { name: "Carl Starfelt", position: "DEF", club: "Celta Vigo" },
  { name: "Herman Johansson", position: "DEF", club: "FC Dallas" },
  { name: "Hjalmar Ekdal", position: "DEF", club: "Burnley" },
  { name: "Daniel Svensson", position: "DEF", club: "Borussia Dortmund" },
  { name: "Eric Smith", position: "MED", club: "FC St Pauli" },
  { name: "Elliot Stroud", position: "MED", club: "Mjallby AIF" },
  { name: "Mattias Svanberg", position: "MED", club: "VfL Wolfsburg" },
  { name: "Jesper Karlström", position: "MED", club: "Udinese" },
  { name: "Yasin Ayari", position: "MED", club: "Brighton & Hove Albion" },
  { name: "Lucas Bergvall", position: "MED", club: "Tottenham Hotspur" },
  { name: "Benjamin Nygren", position: "MED", club: "Celtic" },
  { name: "Ken Sema", position: "MED", club: "Pafos FC" },
  { name: "Besfort Zeneli", position: "MED", club: "Saint-Gilloise" },
  { name: "Taha Ali", position: "DEL", club: "Malmö FF" },
  { name: "Alexander Bernhardsson", position: "DEL", club: "Holstein Kiel" },
  { name: "Anthony Elanga", position: "DEL", club: "Newcastle United" },
  { name: "Viktor Gyökeres", position: "DEL", club: "Arsenal" },
  { name: "Alexander Isak", position: "DEL", club: "Liverpool" },
  { name: "Gustaf Nilsson", position: "DEL", club: "Club Brugge" },
];

// === SUIZA ===
const SUI: RawPlayer[] = [
  { name: "Gregor Kobel", position: "POR", club: "Borussia Dortmund" },
  { name: "Yvon Mvogo", position: "POR", club: "Lorient" },
  { name: "Marvin Keller", position: "POR", club: "Young Boys" },
  { name: "Miro Muheim", position: "DEF", club: "Hamburger SV" },
  { name: "Silvan Widmer", position: "DEF", club: "Mainz 05" },
  { name: "Nico Elvedi", position: "DEF", club: "Borussia Mönchengladbach" },
  { name: "Manuel Akanji", position: "DEF", club: "Inter Milan" },
  { name: "Ricardo Rodriguez", position: "DEF", club: "Real Betis" },
  { name: "Eray Comert", position: "DEF", club: "Valencia" },
  { name: "Aurele Amenda", position: "DEF", club: "Eintracht Frankfurt" },
  { name: "Luca Jaquez", position: "DEF", club: "VfB Stuttgart" },
  { name: "Denis Zakaria", position: "MED", club: "Monaco" },
  { name: "Remo Freuler", position: "MED", club: "Bologna" },
  { name: "Johan Manzambi", position: "MED", club: "SC Freiburg" },
  { name: "Granit Xhaka", position: "MED", club: "Sunderland" },
  { name: "Ardon Jashari", position: "MED", club: "AC Milan" },
  { name: "Djibril Sow", position: "MED", club: "Sevilla" },
  { name: "Christian Fassnacht", position: "MED", club: "Young Boys" },
  { name: "Michel Aebischer", position: "MED", club: "Pisa" },
  { name: "Fabian Rieder", position: "MED", club: "FC Augsburg" },
  { name: "Breel Embolo", position: "DEL", club: "Stade Rennais" },
  { name: "Dan Ndoye", position: "DEL", club: "Nottingham Forest" },
  { name: "Ruben Vargas", position: "DEL", club: "Sevilla" },
  { name: "Noah Okafor", position: "DEL", club: "Leeds United" },
  { name: "Zeki Amdouni", position: "DEL", club: "Burnley" },
  { name: "Cedric Itten", position: "DEL", club: "Fortuna Dusseldorf" },
];

// === TÚNEZ ===
const TUN: RawPlayer[] = [
  { name: "Sabri Ben Hassan", position: "POR", club: "Etoile Sahel" },
  { name: "Abdelmouhib Chamakh", position: "POR", club: "Club Africain" },
  { name: "Aymen Dahmene", position: "POR", club: "CS Sfaxien" },
  { name: "Ali Abdi", position: "DEF", club: "Nice" },
  { name: "Adem Arous", position: "DEF", club: "Kasimpasa" },
  { name: "Mohamed Amine Ben Hamida", position: "DEF", club: "Espérance" },
  { name: "Dylan Bronn", position: "DEF", club: "Servette Geneva" },
  { name: "Raed Chikhaouï", position: "DEF", club: "US Monastir" },
  { name: "Moutaz Neffati", position: "DEF", club: "Norrkoping" },
  { name: "Omar Rekik", position: "DEF", club: "NK Maribor" },
  { name: "Montassar Talbi", position: "DEF", club: "Lorient" },
  { name: "Yan Valery", position: "DEF", club: "Young Boys Berne" },
  { name: "Mortadha Ben Ouanes", position: "MED", club: "Kasimpasa" },
  { name: "Anis Ben Slimane", position: "MED", club: "Norwich City" },
  { name: "Ismael Gharbi", position: "MED", club: "FC Augsburg" },
  { name: "Rani Khedira", position: "MED", club: "Union Berlin" },
  { name: "Mohamed Hadj Mahmoud", position: "MED", club: "Lugano" },
  { name: "Hannibal Mejbri", position: "MED", club: "Burnley" },
  { name: "Ellyes Skhiri", position: "MED", club: "Eintracht Frankfurt" },
  { name: "Elias Achouri", position: "DEL", club: "FC Copenhagen" },
  { name: "Khalil Ayari", position: "DEL", club: "Paris St Germain" },
  { name: "Firas Chaouat", position: "DEL", club: "Club Africain" },
  { name: "Rayan Elloumy", position: "DEL", club: "Vancouver Whitecaps" },
  { name: "Hazem Mastouri", position: "DEL", club: "Dynamo Makhachkala" },
  { name: "Elias Saad", position: "DEL", club: "Hannover 96" },
  { name: "Sebastian Tounekti", position: "DEL", club: "Celtic" },
];

// === URUGUAY ===
const URU: RawPlayer[] = [
  { name: "Sergio Rochet", position: "POR", club: "Internacional" },
  { name: "Fernando Muslera", position: "POR", club: "Estudiantes" },
  { name: "Santiago Mele", position: "POR", club: "Monterrey" },
  { name: "Guillermo Varela", position: "DEF", club: "Flamengo" },
  { name: "Ronald Araújo", position: "DEF", club: "Barcelona" },
  { name: "José María Giménez", position: "DEF", club: "Atlético de Madrid" },
  { name: "Santiago Bueno", position: "DEF", club: "Wolves" },
  { name: "Sebastián Cáceres", position: "DEF", club: "CF América" },
  { name: "Mathías Olivera", position: "DEF", club: "Napoli" },
  { name: "Joaquín Piquerez", position: "DEF", club: "Palmeiras" },
  { name: "Matías Viña", position: "DEF", club: "River Plate" },
  { name: "Manuel Ugarte", position: "MED", club: "Manchester United" },
  { name: "Emiliano Martínez", position: "MED", club: "Palmeiras" },
  { name: "Rodrigo Bentancur", position: "MED", club: "Tottenham Hotspur" },
  { name: "Federico Valverde", position: "MED", club: "Real Madrid" },
  { name: "Agustín Canobbio", position: "MED", club: "Fluminense" },
  { name: "Juan Manuel Sanabria", position: "MED", club: "Real Salt Lake City" },
  { name: "Giorgian de Arrascaeta", position: "MED", club: "Flamengo" },
  { name: "Nicolás de la Cruz", position: "MED", club: "Flamengo" },
  { name: "Rodrigo Zalazar", position: "MED", club: "Braga" },
  { name: "Facundo Pellitri", position: "MED", club: "Panathinaikos" },
  { name: "Maximiliano Araújo", position: "MED", club: "Sporting CP" },
  { name: "Brian Rodríguez", position: "MED", club: "CF América" },
  { name: "Rodrigo Aguirre", position: "DEL", club: "Tigres" },
  { name: "Federico Viñas", position: "DEL", club: "Real Oviedo" },
  { name: "Darwin Núñez", position: "DEL", club: "Al-Hilal" },
];

// === PORTUGAL ===
const POR_SQUAD: RawPlayer[] = [
  { name: "Diogo Costa", position: "POR", club: "FC Porto" },
  { name: "Rui Silva", position: "POR", club: "Sporting CP" },
  { name: "José Sá", position: "POR", club: "Wolverhampton Wanderers" },
  { name: "Rúben Dias", position: "DEF", club: "Manchester City" },
  { name: "Gonçalo Inácio", position: "DEF", club: "Sporting CP" },
  { name: "João Cancelo", position: "DEF", club: "FC Barcelona" },
  { name: "Nuno Mendes", position: "DEF", club: "Paris Saint-Germain" },
  { name: "Diogo Dalot", position: "DEF", club: "Manchester United" },
  { name: "Nélson Semedo", position: "DEF", club: "Fenerbahçe SK" },
  { name: "Tomás Araújo", position: "DEF", club: "Benfica" },
  { name: "Renato Veiga", position: "DEF", club: "Villarreal" },
  { name: "Vitinha", position: "MED", club: "Paris Saint-Germain" },
  { name: "João Neves", position: "MED", club: "Paris Saint-Germain" },
  { name: "Bruno Fernandes", position: "MED", club: "Manchester United" },
  { name: "Rúben Neves", position: "MED", club: "Al-Hilal" },
  { name: "Matheus Nunes", position: "MED", club: "Manchester City" },
  { name: "Samú Costa", position: "MED", club: "Real Mallorca" },
  { name: "Bernardo Silva", position: "MED", club: "Manchester City" },
  { name: "Cristiano Ronaldo", position: "DEL", club: "Al-Nassr" },
  { name: "Francisco Trincão", position: "DEL", club: "Sporting CP" },
  { name: "João Félix", position: "DEL", club: "Al-Nassr" },
  { name: "Gonçalo Ramos", position: "DEL", club: "Paris Saint-Germain" },
  { name: "Pedro Neto", position: "DEL", club: "Chelsea" },
  { name: "Francisco Conceição", position: "DEL", club: "Juventus" },
  { name: "Rafael Leão", position: "DEL", club: "AC Milan" },
  { name: "Gonçalo Guedes", position: "DEL", club: "Real Sociedad" },
];

// === SENEGAL ===
const SEN: RawPlayer[] = [
  { name: "Edouard Mendy", position: "POR", club: "Al-Ahly" },
  { name: "Mory Diaw", position: "POR", club: null },
  { name: "Yehvann Diouf", position: "POR", club: "Dijon FCO" },
  { name: "Antoine Mendy", position: "DEF", club: "Leicester City" },
  { name: "Kalidou Koulibaly", position: "DEF", club: "Al-Hilal" },
  { name: "El Hadji Malick Diouf", position: "DEF", club: null },
  { name: "Mamadou Sarr", position: "DEF", club: null },
  { name: "Moussa Niakhate", position: "DEF", club: "Lens" },
  { name: "Moustapha Mbow", position: "DEF", club: "Watford" },
  { name: "Abdoulaye Seck", position: "DEF", club: "Lorient" },
  { name: "Ismail Jakobs", position: "DEF", club: "OGC Nice" },
  { name: "Idrissa Gana Gueye", position: "MED", club: "Everton" },
  { name: "Pape Gueye", position: "MED", club: "Olympique Marseille" },
  { name: "Lamine Camara", position: "MED", club: "Monaco" },
  { name: "Habib Diarra", position: "MED", club: "Strasbourg" },
  { name: "Pathe Ciss", position: "MED", club: "Metz" },
  { name: "Pape Matar Sarr", position: "MED", club: "Tottenham Hotspur" },
  { name: "Sadio Mané", position: "DEL", club: "Al-Nassr" },
  { name: "Ismaïla Sarr", position: "DEL", club: "Fenerbahçe" },
  { name: "Iliman Ndiaye", position: "DEL", club: "Everton" },
  { name: "Assane Diao", position: "DEL", club: "Real Betis" },
  { name: "Nicolas Jackson", position: "DEL", club: "Chelsea" },
  { name: "Bamba Dieng", position: "DEL", club: "Al-Shabab" },
  { name: "Cherif Ndiaye", position: "DEL", club: "Al-Fayha" },
  { name: "Krepin Diatta", position: "DEL", club: "Monchengladbach" },
  { name: "Ibrahim Mbaye", position: "DEL", club: "Dijon FCO" },
];

// === QATAR ===
const QAT: RawPlayer[] = [
  { name: "Saad Al-Sheeb", position: "POR", club: "Al-Sadd" },
  { name: "Meshaal Barsham", position: "POR", club: "Al-Sadd" },
  { name: "Mohammed Al-Shalawi", position: "POR", club: "Al-Duhail" },
  { name: "Boualem Khoukhi", position: "DEF", club: "Al-Sadd" },
  { name: "Pedro Miguel", position: "DEF", club: "Al-Sadd" },
  { name: "Sultan Al Brake", position: "DEF", club: "Al-Duhail" },
  { name: "Bassam Al-Rawi", position: "DEF", club: "Al-Duhail" },
  { name: "Tarek Salman", position: "DEF", club: "Al-Sadd" },
  { name: "Issa Laye", position: "DEF", club: "Al-Arabi" },
  { name: "Lucas Mendes", position: "DEF", club: "Al-Wakrah" },
  { name: "Ahmed Fathi", position: "MED", club: "Al-Arabi" },
  { name: "Jassim Gaber", position: "MED", club: "Al-Rayyan" },
  { name: "Assim Madibo", position: "MED", club: "Al-Wakrah" },
  { name: "Abdulaziz Hatem", position: "MED", club: "Al-Rayyan" },
  { name: "Karim Boudiaf", position: "MED", club: "Al-Duhail" },
  { name: "Mohammed Mannai", position: "MED", club: "Al-Shamal" },
  { name: "Homam Al-Amin", position: "MED", club: "Cultural Leonesa" },
  { name: "Rayyan Al-Ali", position: "MED", club: "Al-Gharafa" },
  { name: "Almoez Ali", position: "DEL", club: "Al-Duhail" },
  { name: "Akram Afif", position: "DEL", club: "Al-Sadd" },
  { name: "Tahsin Mohammed", position: "DEL", club: "Al-Duhail" },
  { name: "Edmílson Junior", position: "DEL", club: "Al-Duhail" },
  { name: "Ahmed Al-Ganehi", position: "DEL", club: "Al-Gharafa" },
  { name: "Ahmed Alaa", position: "DEL", club: "Al-Rayyan" },
  { name: "Hassan Al-Haydos", position: "DEL", club: "Al-Sadd" },
  { name: "Sebastián Soria", position: "DEL", club: "Qatar SC" },
];

// === PARAGUAY ===
const PAR: RawPlayer[] = [
  { name: "Antony Silva", position: "POR", club: "San Lorenzo" },
  { name: "Roberto Fernández", position: "POR", club: "Al-Wahda" },
  { name: "Alfredo Aguilar", position: "POR", club: "Olimpia" },
  { name: "Gustavo Gómez", position: "DEF", club: "Palmeiras" },
  { name: "Fabián Balbuena", position: "DEF", club: "Nacional" },
  { name: "Omar Alderete", position: "DEF", club: "Getafe" },
  { name: "Santiago Villalba", position: "DEF", club: "Lanús" },
  { name: "Matías Rojas", position: "DEF", club: "Racing Club" },
  { name: "Junior Alonso", position: "DEF", club: "Atlético Mineiro" },
  { name: "Iván Piris", position: "DEF", club: "Internacional" },
  { name: "Diego Viera", position: "DEF", club: "San Lorenzo" },
  { name: "Marcelo Gamarra", position: "DEF", club: "Cerro Porteño" },
  { name: "Blas Riveros", position: "DEF", club: "Huracán" },
  { name: "Andrés Cubas", position: "MED", club: "Nantes" },
  { name: "Miguel Almirón", position: "MED", club: "Real Betis" },
  { name: "Diego Gómez", position: "MED", club: "Brighton" },
  { name: "Ángel Romero", position: "MED", club: "Universidad de Chile" },
  { name: "Mathías Villasanti", position: "MED", club: "Grêmio" },
  { name: "Robert Morales", position: "MED", club: "Olimpia" },
  { name: "Gastón Giménez", position: "MED", club: "FC Juarez" },
  { name: "Carlos González", position: "DEL", club: "Nottingham Forest" },
  { name: "Ramón Sosa", position: "DEL", club: "Nottingham Forest" },
  { name: "Julio Enciso", position: "DEL", club: "Brighton" },
  { name: "Antonio Sanabria", position: "DEL", club: "Torino" },
  { name: "Gabriel Ávalos", position: "DEL", club: "River Plate" },
  { name: "Hernán Pérez", position: "DEL", club: "Colón" },
];

// === TURQUÍA ===
const TUR: RawPlayer[] = [
  { name: "Altay Bayindir", position: "POR", club: "Manchester United" },
  { name: "Mert Günok", position: "POR", club: "Galatasaray" },
  { name: "Ugurcan Çakır", position: "POR", club: "Galatasaray" },
  { name: "Abdulkerim Bardakci", position: "DEF", club: "Galatasaray" },
  { name: "Çağlar Söyüncü", position: "DEF", club: "Fenerbahçe" },
  { name: "Ferdi Kadıoğlu", position: "DEF", club: "Fenerbahçe" },
  { name: "Merih Demiral", position: "DEF", club: "Al-Ahli" },
  { name: "Mert Müldür", position: "DEF", club: "Fenerbahçe" },
  { name: "Ozan Kabak", position: "DEF", club: "Brighton" },
  { name: "Zeki Çelik", position: "DEF", club: "AS Roma" },
  { name: "Atakan Karazor", position: "MED", club: "Sassuolo" },
  { name: "Hakan Çalhanoğlu", position: "MED", club: "Internazionale" },
  { name: "İsmail Yüksek", position: "MED", club: "Fenerbahçe" },
  { name: "Kaan Ayhan", position: "MED", club: "Fortuna Düsseldorf" },
  { name: "Orkun Kökçü", position: "MED", club: "Besiktas" },
  { name: "Salih Özcan", position: "MED", club: "Borussia Dortmund" },
  { name: "Demir Ege Tıknaz", position: "MED", club: "Galatasaray" },
  { name: "Arda Güler", position: "DEL", club: "Real Madrid" },
  { name: "Barış Alper Yılmaz", position: "DEL", club: "Galatasaray" },
  { name: "Can Uzun", position: "DEL", club: "Nuremberg" },
  { name: "İrfan Can Kahveci", position: "DEL", club: "Fenerbahçe" },
  { name: "Kenan Yıldız", position: "DEL", club: "Juventus" },
  { name: "Kerem Aktürkoğlu", position: "DEL", club: "AS Roma" },
  { name: "Oğuz Aydın", position: "DEL", club: "Galatasaray" },
  { name: "Yunus Akgün", position: "DEL", club: "Galatasaray" },
  { name: "Aral Şimşir", position: "DEL", club: "Eintracht Frankfurt" },
];

// === EGIPTO ===
const EGY: RawPlayer[] = [
  { name: "Mohamed El-Shenawy", position: "POR", club: "Al-Ahly" },
  { name: "Mostafa Shobeir", position: "POR", club: "Al-Ahly" },
  { name: "El-Mahdi Soliman", position: "POR", club: "Zamalek" },
  { name: "Mohamed Abdelmonem", position: "DEF", club: "OGC Nice" },
  { name: "Mohamed Hany", position: "DEF", club: "Al-Ahly" },
  { name: "Yasser Ibrahim", position: "DEF", club: "Al-Ahly" },
  { name: "Hossam Abdelmaguid", position: "DEF", club: "Zamalek" },
  { name: "Ahmed Fatouh", position: "DEF", club: "Zamalek" },
  { name: "Rami Rabia", position: "DEF", club: "Al-Ain" },
  { name: "Hamdi Fathi", position: "DEF", club: "Al-Wakrah" },
  { name: "Karim Hafez", position: "DEF", club: "Pyramids" },
  { name: "Tarek Alaa", position: "DEF", club: "ZED" },
  { name: "Marwan Attia", position: "MED", club: "Al-Ahly" },
  { name: "Ahmed Zizo", position: "MED", club: "Al-Ahly" },
  { name: "Mahmoud Hassan Trezeguet", position: "MED", club: "Al-Ahly" },
  { name: "Emam Ashour", position: "MED", club: "Al-Ahly" },
  { name: "Mohannad Lasheen", position: "MED", club: "Pyramids" },
  { name: "Haitham Hassan", position: "MED", club: "Real Oviedo" },
  { name: "Mostafa Abdel Raouf", position: "MED", club: null },
  { name: "Omar Marmoush", position: "DEL", club: "Manchester City" },
  { name: "Mohamed Salah", position: "DEL", club: "Liverpool" },
  { name: "Hamza Abdel Karim", position: "DEL", club: "Nordsjaelland" },
  { name: "Ibrahim Adel", position: "DEL", club: "Nordsjaelland" },
  { name: "Akram Tawfik", position: "DEL", club: null },
  { name: "Ahmed Abdelkader", position: "DEL", club: "Al-Ahly" },
  { name: "Karim Salah", position: "DEL", club: "Sporting CP" },
];

// === ARABIA SAUDITA ===
const KSA: RawPlayer[] = [
  { name: "Mohammed Al-Owais", position: "POR", club: "Al-Hilal" },
  { name: "Nawaf Al-Aqidi", position: "POR", club: "Al-Fayha" },
  { name: "Mohammed Al-Rubaie", position: "POR", club: "Al-Ahli" },
  { name: "Hassan Tambakti", position: "DEF", club: "Al-Hilal" },
  { name: "Jehad Thikri", position: "DEF", club: "Al-Qadsiah" },
  { name: "Ali Lajami", position: "DEF", club: "Al-Hilal" },
  { name: "Saud Abdulhamid", position: "DEF", club: "RC Lens" },
  { name: "Ali Majrashi", position: "DEF", club: "Al-Ahli" },
  { name: "Moteb Al Harbi", position: "DEF", club: "Al-Hilal" },
  { name: "Nawaf Boushal", position: "DEF", club: "Al-Nassr" },
  { name: "Sultan Al-Ghannam", position: "DEF", club: "Al-Nassr" },
  { name: "Mohammed Abu Al Shamat", position: "DEF", club: "Al-Qadsiah" },
  { name: "Abdulelah Al Amri", position: "DEF", club: "Al-Nassr" },
  { name: "Mohammed Kanno", position: "MED", club: "Al-Hilal" },
  { name: "Abdullah Al Khaibari", position: "MED", club: "Al-Nassr" },
  { name: "Nasser Al-Dawsari", position: "MED", club: "Al-Hilal" },
  { name: "Musab Al Juwayr", position: "MED", club: "Al-Qadsiah" },
  { name: "Salem Al-Dawsari", position: "MED", club: "Al-Hilal" },
  { name: "Khalid Al Ghannam", position: "MED", club: "Al-Ettifaq" },
  { name: "Ayman Yahya", position: "MED", club: "Al-Nassr" },
  { name: "Ziyad Al Johani", position: "MED", club: "Al-Ahli" },
  { name: "Alaa Al Hajji", position: "MED", club: "Neom" },
  { name: "Firas Al-Buraikan", position: "DEL", club: "Al-Ahli" },
  { name: "Saleh Al-Shehri", position: "DEL", club: "Al-Ittihad" },
  { name: "Abdullah Al-Hamdan", position: "DEL", club: "Al-Nassr" },
  { name: "Hassan Kadesh", position: "DEL", club: "Al-Ittihad" },
];

// === IRÁN ===
const IRN: RawPlayer[] = [
  { name: "Alireza Beiranvand", position: "POR", club: "Persepolis" },
  { name: "Hossein Hosseini", position: "POR", club: "Persepolis" },
  { name: "Payam Niazmand", position: "POR", club: "Esteghlal" },
  { name: "Danial Eiri", position: "DEF", club: "Esteghlal" },
  { name: "Ehsan Hajsafi", position: "DEF", club: "Trabzonspor" },
  { name: "Saleh Hardani", position: "DEF", club: "Saipa" },
  { name: "Hossein Kanaani", position: "DEF", club: "Persepolis" },
  { name: "Shoja Khalilzadeh", position: "DEF", club: "AEK Athens" },
  { name: "Milad Mohammadi", position: "DEF", club: "Atalanta" },
  { name: "Ali Nemati", position: "DEF", club: "Persepolis" },
  { name: "Ramin Rezaeian", position: "DEF", club: null },
  { name: "Rouzbeh Cheshmi", position: "MED", club: "Sunderland" },
  { name: "Saeid Ezatolahi", position: "MED", club: "Volga Nizhny Novgorod" },
  { name: "Mehdi Ghaedi", position: "MED", club: "Esteghlal" },
  { name: "Saman Ghoddos", position: "MED", club: "Brentford" },
  { name: "Mohammad Ghorbani", position: "MED", club: "Persepolis" },
  { name: "Alireza Jahanbakhsh", position: "MED", club: "AEK Athens" },
  { name: "Mohammad Mohebi", position: "MED", club: "Esteghlal" },
  { name: "Amir Mohammad Razzaghinia", position: "MED", club: "Persepolis" },
  { name: "Mehdi Taremi", position: "DEL", club: "Olympiacos" },
  { name: "Ali Alipour", position: "DEL", club: "Kaiserslautern" },
  { name: "Amirhossein Hosseinzadeh", position: "DEL", club: "Al-Fayha" },
  { name: "Hadi Habibinejad", position: "DEL", club: "Persepolis" },
  { name: "Kasra Taheri", position: "DEL", club: null },
  { name: "Mehdi Torabi", position: "DEL", club: null },
  { name: "Aria Yousefi", position: "DEL", club: "Volos NFC" },
];

// === IRAK ===
const IRQ: RawPlayer[] = [
  { name: "Ahmed Basil", position: "POR", club: "Beerschot" },
  { name: "Jalal Hassan", position: "POR", club: "Al-Zawraa" },
  { name: "Fahad Talib", position: "POR", club: "Al-Zawraa" },
  { name: "Ali Adnan", position: "DEF", club: "Colorado Rapids" },
  { name: "Ali Faez", position: "DEF", club: "Al-Zawraa" },
  { name: "Hussein Ali", position: "DEF", club: "Al-Zawraa" },
  { name: "Rebin Sulaka", position: "DEF", club: "Hammarby" },
  { name: "Mustafa Nadhim", position: "DEF", club: "Al-Zawraa" },
  { name: "Amjad Kalaf", position: "DEF", club: "Al-Zawraa" },
  { name: "Hmood Almosawi", position: "DEF", club: "Al-Shorta" },
  { name: "Kevin Yakob", position: "DEF", club: null },
  { name: "Amjad Attwan", position: "MED", club: "Al-Zawraa" },
  { name: "Safaa Hadi", position: "MED", club: "Al-Zawraa" },
  { name: "Zidane Iqbal", position: "MED", club: "Utrecht" },
  { name: "Aimar Sher", position: "MED", club: "Heerenveen" },
  { name: "Ali Jassim", position: "MED", club: null },
  { name: "Amir Al-Ammari", position: "MED", club: null },
  { name: "Osama Rashid", position: "MED", club: "Al-Shorta" },
  { name: "Mohanad Ali", position: "MED", club: "Al-Zawraa" },
  { name: "Aymen Hussein", position: "DEL", club: "Al-Zawraa" },
  { name: "Ali Al-Hamadi", position: "DEL", club: "Ipswich Town" },
  { name: "Alaa Abbas", position: "DEL", club: "Al-Zawraa" },
  { name: "Ibrahim Bayesh", position: "DEL", club: "Al-Shorta" },
  { name: "Ahmed Yasin", position: "DEL", club: "Al-Zawraa" },
  { name: "Emad Mohammed", position: "DEL", club: "Al-Zawraa" },
  { name: "Bassam Rashed", position: "DEL", club: "Al-Diwaniya" },
];

// === JORDANIA ===
const JOR: RawPlayer[] = [
  { name: "Yazid Abulaila", position: "POR", club: "Al-Hussein" },
  { name: "Abdallah Al Fakhouri", position: "POR", club: "Al-Wehdat" },
  { name: "Nour Bani Attiah", position: "POR", club: "Al-Faisaly" },
  { name: "Mohammad Abualnadi", position: "DEF", club: "Selangor" },
  { name: "Yousef Abu Al Jazar", position: "DEF", club: "Al-Hussein" },
  { name: "Husam Abu Dahab", position: "DEF", club: "Al-Samiya" },
  { name: "Mohammad Abu Hashish", position: "DEF", club: "Al-Karma" },
  { name: "Yazan Al Arab", position: "DEF", club: "Suwon Samsung Bluewings" },
  { name: "Abdallah Nasib", position: "DEF", club: "Al-Zawraa" },
  { name: "Saleem Obaid", position: "DEF", club: "Al-Hussein" },
  { name: "Omar Al-Dmeiri", position: "DEF", club: "Al-Hayat" },
  { name: "Mohammad Al Dawoud", position: "MED", club: "Al-Wehdat" },
  { name: "Nizar Al Rashdan", position: "MED", club: "Qatar SC" },
  { name: "Noor Al Rawabdeh", position: "MED", club: "Selangor" },
  { name: "Rajaei Ayed", position: "MED", club: "Al-Hussein" },
  { name: "Amer Jamous", position: "MED", club: "Al-Zawraa" },
  { name: "Yousef Qashi", position: "MED", club: null },
  { name: "Ibrahim Sadeh", position: "MED", club: "Al-Karma" },
  { name: "Ahmad Eid", position: "MED", club: "Al-Faisaly" },
  { name: "Mousa Al Tamari", position: "DEL", club: "Stade Rennais" },
  { name: "Mahmoud Al-Mardi", position: "DEL", club: "Al-Hussein" },
  { name: "Mohannad Abu Taha", position: "DEL", club: "Al-Quwa" },
  { name: "Yazan Al-Naimat", position: "DEL", club: "Al-Arabi" },
  { name: "Ali Olwan", position: "DEL", club: "Al-Sailiya" },
  { name: "Ibrahim Sabra", position: "DEL", club: "Dinamo Zagreb" },
  { name: "Baha Faisal", position: "DEL", club: "Al-Faisaly" },
];

// === UZBEKISTÁN ===
const UZB: RawPlayer[] = [
  { name: "O'tkir Yusupov", position: "POR", club: "Pakhtakor" },
  { name: "Botirali Ergashev", position: "POR", club: "Navbahor" },
  { name: "Abduvohid Ne'matov", position: "POR", club: null },
  { name: "Abdukodir Khusanov", position: "DEF", club: "Manchester City" },
  { name: "Khojiakbar Alijonov", position: "DEF", club: null },
  { name: "Igor Sergeyev", position: "DEF", club: null },
  { name: "Sanjar Tursunov", position: "DEF", club: "Pakhtakor" },
  { name: "Jasurbek Yakhshiboev", position: "DEF", club: "Pakhtakor" },
  { name: "Dostonbek Khamdamov", position: "DEF", club: null },
  { name: "Behruzbek Shomurodov", position: "DEF", club: "Pakhtakor" },
  { name: "Sherzod Esanov", position: "MED", club: "Lokomotiv Moscow" },
  { name: "Odil Hamrobekov", position: "MED", club: "Pakhtakor" },
  { name: "Akmal Mozgovoy", position: "MED", club: null },
  { name: "Otabek Shukurov", position: "MED", club: "Al-Wasl" },
  { name: "Jamshid Iskanderov", position: "MED", club: null },
  { name: "Jasur Jaloliddinov", position: "MED", club: "Pakhtakor" },
  { name: "Aziz G'aniyev", position: "MED", club: null },
  { name: "Umarali Rahmonaliyev", position: "MED", club: null },
  { name: "Sherzod Temirov", position: "MED", club: "Pakhtakor" },
  { name: "Eldor Shomurodov", position: "DEL", club: "Istanbul Basaksehir" },
  { name: "Abbos Fayzullayev", position: "DEL", club: "Al-Shamal" },
  { name: "Jaloliddin Masharipov", position: "DEL", club: null },
  { name: "Doston Hamdamov", position: "DEL", club: "Pakhtakor" },
  { name: "Oston O'runov", position: "DEL", club: null },
  { name: "Aziz Amonov", position: "DEL", club: "Pakhtakor" },
  { name: "Ruslan Jiyanov", position: "DEL", club: null },
];

// === GHANA ===
const GHA: RawPlayer[] = [
  { name: "Lawrence Ati-Zigi", position: "POR", club: "St Gallen" },
  { name: "Ibrahim Danlad", position: "POR", club: "Asante Kotoko" },
  { name: "Richard Ofori", position: "POR", club: "Orlando Pirates" },
  { name: "Abdul Manaf Nurudeen", position: "POR", club: "Eupen" },
  { name: "Alexander Djiku", position: "DEF", club: "Fenerbahçe" },
  { name: "Daniel Amartey", position: "DEF", club: "Besiktas" },
  { name: "Gideon Mensah", position: "DEF", club: "Auxerre" },
  { name: "Baba Abdul Rahman", position: "DEF", club: "Al-Wehdat" },
  { name: "Mohammed Salisu", position: "DEF", club: "Southampton" },
  { name: "Tariq Lamptey", position: "DEF", club: "Brighton" },
  { name: "Dennis Odoi", position: "DEF", club: "Club Brugge" },
  { name: "Alidu Seidu", position: "DEF", club: "Clermont Foot" },
  { name: "Thomas Partey", position: "MED", club: "Villarreal" },
  { name: "Elisha Owusu", position: "MED", club: "AZ Alkmaar" },
  { name: "Abdul Fatawu", position: "MED", club: "Leicester City" },
  { name: "Daniel Kofi Kyereh", position: "MED", club: "Freiburg" },
  { name: "Salis Abdul Samed", position: "MED", club: "RC Lens" },
  { name: "Majeed Ashimeru", position: "MED", club: "Anderlecht" },
  { name: "Emmanuel Lomotey", position: "MED", club: "Ferencváros" },
  { name: "Iñaki Williams", position: "DEL", club: "Athletic Club" },
  { name: "Antoine Semenyo", position: "DEL", club: "Manchester City" },
  { name: "Jordan Ayew", position: "DEL", club: "Leicester City" },
  { name: "Ernest Nuamah", position: "DEL", club: "Olympique Lyonnais" },
  { name: "Christopher Bonsu Baah", position: "DEL", club: "Al-Qadsiah" },
  { name: "Kamal Deen Sulemana", position: "DEL", club: "Atlanta United" },
  { name: "Brandon Thomas-Asante", position: "DEL", club: "Coventry City" },
];

// === REGISTRO COMPLETO ===
const REAL_SQUADS: Record<string, { players: RawPlayer[]; stars: string[] }> = {
  ger: { players: GER, stars: ["Florian Wirtz", "Jamal Musiala", "Kai Havertz", "Joshua Kimmich"] },
  alg: { players: ALG, stars: ["Riyad Mahrez", "Amine Gouiri", "Mohamed Amine Amoura"] },
  arg: { players: ARG, stars: ["Lionel Messi", "Lautaro Martínez", "Emiliano Martínez", "Enzo Fernández"] },
  aus: { players: AUS, stars: ["Mathew Ryan", "Jackson Irvine", "Nestory Irankunda"] },
  aut: { players: AUT, stars: ["David Alaba", "Marko Arnautović", "Marcel Sabitzer"] },
  bel: { players: BEL, stars: ["Kevin De Bruyne", "Romelu Lukaku", "Jeremy Doku", "Thibaut Courtois"] },
  bih: { players: BIH, stars: ["Edin Dzeko", "Ermedin Demirovic"] },
  bra: { players: BRA, stars: ["Vinícius Júnior", "Neymar", "Marquinhos", "Raphinha"] },
  cpv: { players: CPV, stars: ['Josimar Dias "Vozinha"', "Logan Costa", "Jovane Cabral"] },
  can: { players: CAN, stars: ["Alphonso Davies", "Jonathan David", "Stephen Eustáquio"] },
  col: { players: COL, stars: ["Luis Díaz", "James Rodríguez", "Davinson Sánchez"] },
  kor: { players: KOR, stars: ["Son Heung-min", "Kim Min-jae", "Lee Kang-in"] },
  civ: { players: CIV, stars: ["Franck Kessié", "Amad Diallo", "Ibrahim Sangaré"] },
  cze: { players: CZE, stars: ["Patrik Schick", "Tomáš Souček", "Matěj Kovář"] },
  cro: { players: CRO, stars: ["Luka Modrić", "Joško Gvardiol", "Mateo Kovačić"] },
  cuw: { players: CUW, stars: ["Tahith Chong", "Jurgen Locadia", "Leandro Bacuna"] },
  ecu: { players: ECU, stars: ["Moisés Caicedo", "Enner Valencia", "Piero Hincapié"] },
  sco: { players: SCO, stars: ["Andy Robertson", "Scott McTominay", "John McGinn"] },
  esp: { players: ESP, stars: ["Lamine Yamal", "Rodrigo Hernández (Rodri)", "Pedri González", "Nico Williams"] },
  usa: { players: USA, stars: ["Christian Pulisic", "Weston McKennie", "Folarin Balogun"] },
  fra: { players: FRA, stars: ["Kylian Mbappé", "Ousmane Dembélé", "Aurélien Tchouaméni", "Mike Maignan"] },
  hai: { players: HAI, stars: ["Jean-Ricner Bellegarde", "Wilson Isidor"] },
  ing: { players: ING, stars: ["Harry Kane", "Jude Bellingham", "Bukayo Saka", "Declan Rice"] },
  jpn: { players: JPN, stars: ["Wataru Endo", "Takefusa Kubo", "Daizen Maeda"] },
  mar: { players: MAR, stars: ["Achraf Hakimi", "Brahim Díaz", "Yassine Bounou", "Sofyan Amrabat"] },
  mex: { players: MEX, stars: ["Santiago Giménez", "Edson Álvarez", "Guillermo Ochoa"] },
  nor: { players: NOR, stars: ["Erling Haaland", "Martin Ødegaard", "Alexander Sørloth"] },
  nzl: { players: NZL, stars: ["Chris Wood", "Marko Stamenić"] },
  ned: { players: NED, stars: ["Virgil van Dijk", "Cody Gakpo", "Frenkie de Jong", "Tijjani Reijnders"] },
  pan: { players: PAN, stars: ["Aníbal Godoy", "Adalberto Carrasquilla", "Ismael Diaz"] },
  cod: { players: COD, stars: ["Yoane Wissa", "Cédric Bakambu", "Chancel Mbemba"] },
  rsa: { players: RSA, stars: ["Ronwen Williams", "Lyle Foster", "Teboho Mokoena"] },
  swe: { players: SWE, stars: ["Viktor Gyökeres", "Alexander Isak", "Victor Lindelöf"] },
  sui: { players: SUI, stars: ["Granit Xhaka", "Breel Embolo", "Manuel Akanji"] },
  tun: { players: TUN, stars: ["Ellyes Skhiri", "Hannibal Mejbri"] },
  uru: { players: URU, stars: ["Federico Valverde", "Darwin Núñez", "Ronald Araújo", "Manuel Ugarte"] },
  por: { players: POR_SQUAD, stars: ["Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva", "Rafael Leão"] },
  sen: { players: SEN, stars: ["Sadio Mané", "Kalidou Koulibaly", "Nicolas Jackson"] },
  qat: { players: QAT, stars: ["Akram Afif", "Almoez Ali", "Hassan Al-Haydos"] },
  par: { players: PAR, stars: ["Miguel Almirón", "Julio Enciso", "Diego Gómez"] },
  tur: { players: TUR, stars: ["Hakan Çalhanoğlu", "Arda Güler", "Kenan Yıldız"] },
  egy: { players: EGY, stars: ["Mohamed Salah", "Omar Marmoush"] },
  ksa: { players: KSA, stars: ["Salem Al-Dawsari", "Firas Al-Buraikan", "Saud Abdulhamid"] },
  irn: { players: IRN, stars: ["Mehdi Taremi", "Alireza Beiranvand", "Ehsan Hajsafi"] },
  irq: { players: IRQ, stars: ["Aymen Hussein", "Ali Al-Hamadi", "Zidane Iqbal"] },
  jor: { players: JOR, stars: ["Mousa Al Tamari", "Ibrahim Sabra"] },
  uzb: { players: UZB, stars: ["Eldor Shomurodov", "Abdukodir Khusanov"] },
  gha: { players: GHA, stars: ["Thomas Partey", "Iñaki Williams", "Jordan Ayew"] },
};

export function getRealRoster(teamId: string): Player[] | null {
  const squad = REAL_SQUADS[teamId];
  if (!squad) return null;
  return build(teamId, squad.players, squad.stars);
}

export function hasRealRoster(teamId: string): boolean {
  return teamId in REAL_SQUADS;
}

