/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisPronosticosRouteImport } from './routes/mis-pronosticos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FixtureRouteImport } from './routes/fixture'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as BolaDeCristalRouteImport } from './routes/bola-de-cristal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EquiposEquipoIdRouteImport } from './routes/equipos.$equipoId'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminPredictorRouteImport } from './routes/admin.predictor'
import { Route as AdminPartidosRouteImport } from './routes/admin.partidos'
import { Route as AdminJugadoresRouteImport } from './routes/admin.jugadores'
import { Route as ApiPublicCronSyncResultsRouteImport } from './routes/api.public.cron.sync-results'

const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPronosticosRoute = MisPronosticosRouteImport.update({
  id: '/mis-pronosticos',
  path: '/mis-pronosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureRoute = FixtureRouteImport.update({
  id: '/fixture',
  path: '/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const BolaDeCristalRoute = BolaDeCristalRouteImport.update({
  id: '/bola-de-cristal',
  path: '/bola-de-cristal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EquiposEquipoIdRoute = EquiposEquipoIdRouteImport.update({
  id: '/$equipoId',
  path: '/$equipoId',
  getParentRoute: () => EquiposRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPredictorRoute = AdminPredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartidosRoute = AdminPartidosRouteImport.update({
  id: '/partidos',
  path: '/partidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJugadoresRoute = AdminJugadoresRouteImport.update({
  id: '/jugadores',
  path: '/jugadores',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronSyncResultsRoute =
  ApiPublicCronSyncResultsRouteImport.update({
    id: '/api/public/cron/sync-results',
    path: '/api/public/cron/sync-results',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bola-de-cristal': typeof BolaDeCristalRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/reglas': typeof ReglasRoute
  '/admin/jugadores': typeof AdminJugadoresRoute
  '/admin/partidos': typeof AdminPartidosRoute
  '/admin/predictor': typeof AdminPredictorRoute
  '/admin/sync': typeof AdminSyncRoute
  '/equipos/$equipoId': typeof EquiposEquipoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cron/sync-results': typeof ApiPublicCronSyncResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bola-de-cristal': typeof BolaDeCristalRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/reglas': typeof ReglasRoute
  '/admin/jugadores': typeof AdminJugadoresRoute
  '/admin/partidos': typeof AdminPartidosRoute
  '/admin/predictor': typeof AdminPredictorRoute
  '/admin/sync': typeof AdminSyncRoute
  '/equipos/$equipoId': typeof EquiposEquipoIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/cron/sync-results': typeof ApiPublicCronSyncResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bola-de-cristal': typeof BolaDeCristalRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/reglas': typeof ReglasRoute
  '/admin/jugadores': typeof AdminJugadoresRoute
  '/admin/partidos': typeof AdminPartidosRoute
  '/admin/predictor': typeof AdminPredictorRoute
  '/admin/sync': typeof AdminSyncRoute
  '/equipos/$equipoId': typeof EquiposEquipoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cron/sync-results': typeof ApiPublicCronSyncResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bola-de-cristal'
    | '/equipos'
    | '/fixture'
    | '/insights'
    | '/login'
    | '/mis-pronosticos'
    | '/perfil'
    | '/ranking'
    | '/registro'
    | '/reglas'
    | '/admin/jugadores'
    | '/admin/partidos'
    | '/admin/predictor'
    | '/admin/sync'
    | '/equipos/$equipoId'
    | '/admin/'
    | '/api/public/cron/sync-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bola-de-cristal'
    | '/equipos'
    | '/fixture'
    | '/insights'
    | '/login'
    | '/mis-pronosticos'
    | '/perfil'
    | '/ranking'
    | '/registro'
    | '/reglas'
    | '/admin/jugadores'
    | '/admin/partidos'
    | '/admin/predictor'
    | '/admin/sync'
    | '/equipos/$equipoId'
    | '/admin'
    | '/api/public/cron/sync-results'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bola-de-cristal'
    | '/equipos'
    | '/fixture'
    | '/insights'
    | '/login'
    | '/mis-pronosticos'
    | '/perfil'
    | '/ranking'
    | '/registro'
    | '/reglas'
    | '/admin/jugadores'
    | '/admin/partidos'
    | '/admin/predictor'
    | '/admin/sync'
    | '/equipos/$equipoId'
    | '/admin/'
    | '/api/public/cron/sync-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BolaDeCristalRoute: typeof BolaDeCristalRoute
  EquiposRoute: typeof EquiposRouteWithChildren
  FixtureRoute: typeof FixtureRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MisPronosticosRoute: typeof MisPronosticosRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  RegistroRoute: typeof RegistroRoute
  ReglasRoute: typeof ReglasRoute
  ApiPublicCronSyncResultsRoute: typeof ApiPublicCronSyncResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pronosticos': {
      id: '/mis-pronosticos'
      path: '/mis-pronosticos'
      fullPath: '/mis-pronosticos'
      preLoaderRoute: typeof MisPronosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture': {
      id: '/fixture'
      path: '/fixture'
      fullPath: '/fixture'
      preLoaderRoute: typeof FixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bola-de-cristal': {
      id: '/bola-de-cristal'
      path: '/bola-de-cristal'
      fullPath: '/bola-de-cristal'
      preLoaderRoute: typeof BolaDeCristalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/equipos/$equipoId': {
      id: '/equipos/$equipoId'
      path: '/$equipoId'
      fullPath: '/equipos/$equipoId'
      preLoaderRoute: typeof EquiposEquipoIdRouteImport
      parentRoute: typeof EquiposRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/predictor': {
      id: '/admin/predictor'
      path: '/predictor'
      fullPath: '/admin/predictor'
      preLoaderRoute: typeof AdminPredictorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partidos': {
      id: '/admin/partidos'
      path: '/partidos'
      fullPath: '/admin/partidos'
      preLoaderRoute: typeof AdminPartidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jugadores': {
      id: '/admin/jugadores'
      path: '/jugadores'
      fullPath: '/admin/jugadores'
      preLoaderRoute: typeof AdminJugadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/sync-results': {
      id: '/api/public/cron/sync-results'
      path: '/api/public/cron/sync-results'
      fullPath: '/api/public/cron/sync-results'
      preLoaderRoute: typeof ApiPublicCronSyncResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminJugadoresRoute: typeof AdminJugadoresRoute
  AdminPartidosRoute: typeof AdminPartidosRoute
  AdminPredictorRoute: typeof AdminPredictorRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJugadoresRoute: AdminJugadoresRoute,
  AdminPartidosRoute: AdminPartidosRoute,
  AdminPredictorRoute: AdminPredictorRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EquiposRouteChildren {
  EquiposEquipoIdRoute: typeof EquiposEquipoIdRoute
}

const EquiposRouteChildren: EquiposRouteChildren = {
  EquiposEquipoIdRoute: EquiposEquipoIdRoute,
}

const EquiposRouteWithChildren =
  EquiposRoute._addFileChildren(EquiposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BolaDeCristalRoute: BolaDeCristalRoute,
  EquiposRoute: EquiposRouteWithChildren,
  FixtureRoute: FixtureRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MisPronosticosRoute: MisPronosticosRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  RegistroRoute: RegistroRoute,
  ReglasRoute: ReglasRoute,
  ApiPublicCronSyncResultsRoute: ApiPublicCronSyncResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
