/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisPronosticosRouteImport } from './routes/mis-pronosticos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FixtureRouteImport } from './routes/fixture'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as BolaDeCristalRouteImport } from './routes/bola-de-cristal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquiposEquipoIdRouteImport } from './routes/equipos.$equipoId'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPronosticosRoute = MisPronosticosRouteImport.update({
  id: '/mis-pronosticos',
  path: '/mis-pronosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureRoute = FixtureRouteImport.update({
  id: '/fixture',
  path: '/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const BolaDeCristalRoute = BolaDeCristalRouteImport.update({
  id: '/bola-de-cristal',
  path: '/bola-de-cristal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposEquipoIdRoute = EquiposEquipoIdRouteImport.update({
  id: '/$equipoId',
  path: '/$equipoId',
  getParentRoute: () => EquiposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bola-de-cristal': typeof BolaDeCristalRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/equipos/$equipoId': typeof EquiposEquipoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bola-de-cristal': typeof BolaDeCristalRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/equipos/$equipoId': typeof EquiposEquipoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bola-de-cristal': typeof BolaDeCristalRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registro': typeof RegistroRoute
  '/equipos/$equipoId': typeof EquiposEquipoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bola-de-cristal'
    | '/equipos'
    | '/fixture'
    | '/insights'
    | '/login'
    | '/mis-pronosticos'
    | '/perfil'
    | '/ranking'
    | '/registro'
    | '/equipos/$equipoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bola-de-cristal'
    | '/equipos'
    | '/fixture'
    | '/insights'
    | '/login'
    | '/mis-pronosticos'
    | '/perfil'
    | '/ranking'
    | '/registro'
    | '/equipos/$equipoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bola-de-cristal'
    | '/equipos'
    | '/fixture'
    | '/insights'
    | '/login'
    | '/mis-pronosticos'
    | '/perfil'
    | '/ranking'
    | '/registro'
    | '/equipos/$equipoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BolaDeCristalRoute: typeof BolaDeCristalRoute
  EquiposRoute: typeof EquiposRouteWithChildren
  FixtureRoute: typeof FixtureRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MisPronosticosRoute: typeof MisPronosticosRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pronosticos': {
      id: '/mis-pronosticos'
      path: '/mis-pronosticos'
      fullPath: '/mis-pronosticos'
      preLoaderRoute: typeof MisPronosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture': {
      id: '/fixture'
      path: '/fixture'
      fullPath: '/fixture'
      preLoaderRoute: typeof FixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bola-de-cristal': {
      id: '/bola-de-cristal'
      path: '/bola-de-cristal'
      fullPath: '/bola-de-cristal'
      preLoaderRoute: typeof BolaDeCristalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$equipoId': {
      id: '/equipos/$equipoId'
      path: '/$equipoId'
      fullPath: '/equipos/$equipoId'
      preLoaderRoute: typeof EquiposEquipoIdRouteImport
      parentRoute: typeof EquiposRoute
    }
  }
}

interface EquiposRouteChildren {
  EquiposEquipoIdRoute: typeof EquiposEquipoIdRoute
}

const EquiposRouteChildren: EquiposRouteChildren = {
  EquiposEquipoIdRoute: EquiposEquipoIdRoute,
}

const EquiposRouteWithChildren =
  EquiposRoute._addFileChildren(EquiposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BolaDeCristalRoute: BolaDeCristalRoute,
  EquiposRoute: EquiposRouteWithChildren,
  FixtureRoute: FixtureRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MisPronosticosRoute: MisPronosticosRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
